# -*- coding: utf-8 -*-
"""Frasi leggibili degli anelli.

I valori numerici restano nel database PROC_ANELLI: qui ci sono solo frasi
pensate per il giocatore, con placeholder risolti a runtime da nft.py.
"""

FRASI_ANELLI_TECNICHE = {
    "Anello perfezionista": "Se vuoi una sfida perfettamente ripetibile, questo anello fissa il destino usando il seed {generale.seed}: le estrazioni casuali seguiranno sempre la stessa sequenza.",
    "Cinta del comandante": "Nel {turno.comando.proc:pct} dei turni riesci a imporre il tuo comando e riduci l'attacco del nemico di {turno.comando.atk_target_base} più la tua INT.",
    "Amuleto del protettore": "Nel {turno.protezione.proc:pct} dei turni ti fai enorme per proteggerti: aggiungi alla difesa un altro blocco pari alla tua difesa, scalato dal tuo bonus, con moltiplicatore {turno.protezione.moltiplicatore_bonus:x}.",
    "Guanto titanico": "Nel {turno.difesa.proc:pct} dei turni la tua presenza spegne quasi del tutto il colpo avversario, portandone la base a {turno.difesa.dps_base} prima di sottrarre la sua INT.",
    "Stemma della rocca": "Nel {turno.rocca.proc:pct} dei turni la rocca ti rende più resistente: guadagni {turno.rocca.def_base} difesa più la tua INT.",
    "Un frammento del potere": "È piccolo solo fuori: ha il {turno.attacco.proc:pct} di liberare il suo potere quando attacchi e il {turno.difesa.proc:pct} quando difendi, trasformandosi nell'anello più assurdo del gioco.",
    "Un generatore incartato": "A fine sfida hai il {ricompense.incartato.proc:pct} di trovare {ricompense.incartato.quantita} Oggetto incartato extra.",
    "Occhio del falco": "Negli assalti aiuti ogni compagno con almeno {assalto.aura.minimo} AGI, oppure con il {assalto.aura.percento_stat:pct} della tua AGI se il risultato è maggiore.",
    "Carica mobile": "Negli assalti hai il {assalto.esplosione.proc:pct} di far saltare una parte della difesa nemica con un'esplosione da {assalto.esplosione.danno_min} a {assalto.esplosione.danno_max} danni.",
    "Ricordo straziante": "Nel {turno.intangibile.proc:pct} dei turni svanisci per un istante e il colpo ti attraversa senza fare nulla: danno e modificatore vengono portati a {turno.intangibile.danno}.",
    "Chiavi dell'aldilà": "Quando sembrava finita, hai il {turno.resurrezione.proc:pct} di riaprire la porta dell'aldilà e tornare in piedi con una base di {turno.resurrezione.hp_base} HP.",
    "Cuore delle sabbie": "Hai il {turno.insabbiato.proc:pct} di sommergere il nemico nelle sabbie: parte da livello {turno.insabbiato.lv}, dura {turno.insabbiato.dur} turno e può crescere di {turno.insabbiato.lv_incremento:signed} livello.",
    "Tasto B": "Hai il {turno.roll.proc:pct} di cavartela con una schivata perfetta e portare il modificatore del colpo a {turno.roll.mod}, evitando completamente il danno.",
    "Tasto X": "Hai il {turno.obliteratore.proc:pct} di far esplodere il colpo avversario in un lampo: la sua forza viene divisa per {turno.obliteratore.divisore_mod} e l'effetto parte da un bonus di {turno.obliteratore.bonus_stat_base}.",
    "Coda demoniaca": "Quando schivi prepari il terreno per far soffrire il nemico. Più danno c'è in gioco, più cresce la possibilità di bloccarlo completamente; il calcolo usa {turno.dolore.divisore_chance} danni come riferimento e Demone spezza-ossa aggiunge {turno.dolore.bonus_speciale} al bonus.",
    "Anello superfortissimo ma proprio rotto sgravatissimo": "È l'anello da debug volutamente fuori scala: se compare, il gioco ha deciso di smettere di fingere di essere bilanciato.",
    "Stemma del leader": "Negli assalti aiuti ogni compagno con almeno {assalto.aura.minimo} ATK, oppure con il {assalto.aura.percento_stat:pct} del tuo ATK se il risultato è maggiore.",
    "Chiavi": "Nel {turno.batmobile.proc:pct} dei turni trovi finalmente il veicolo giusto: arriva la Batmobile e aggiunge {turno.batmobile.danno} danni al caos.",
    "Aura pessima": "La tua sola presenza rende la difesa nemica meno efficace: la porti all'{turno.aura.moltiplicatore_difesa_target:pct_mul} del suo valore normale, cioè la riduci del {turno.aura.moltiplicatore_difesa_target:rid_pct}.",
    "Fanghiglia della palude": "Finché hai almeno {turno.fango.hp_min} HP, nel {turno.fango.proc:pct} dei turni la fanghiglia ti trasforma: guadagni {turno.fango.atk:signed} attacco e {turno.fango.def:signed} difesa, ma spendi {turno.fango.hp:abs} HP.",
    "Anello dell'occulto": "Se il nemico schiva, hai il {turno.trascinamento.proc:pct} di trascinarlo comunque nel colpo: il contraccolpo usa circa un terzo del danno e può oscillare tra {turno.trascinamento.random_min:x} e {turno.trascinamento.random_max:x}.",
    "Effige della tribe": "Nel {turno.cura_spettrale.proc:pct} dei turni, finché sei sotto {turno.cura_spettrale.hp_max} HP, gli spiriti ti curano del {turno.cura_spettrale.cura_percento_hp:pct} dei tuoi HP. Per l'Ipposciamano indemoniato la possibilità sale all'{turno.cura_spettrale.speciali.Ipposciamano indemoniato.proc:pct} e funziona fino a {turno.cura_spettrale.speciali.Ipposciamano indemoniato.hp_max} HP.",
    "Scarica di adrenalina": "Quando vieni colpito senza schivare hai il {turno.adrenalina.proc:pct} di trasformare il dolore in attacco: al danno ricevuto vengono aggiunti {turno.adrenalina.offset_danno}, poi il valore viene diviso per {turno.adrenalina.divisore} e infine riceve un altro {turno.adrenalina.bonus_finale:signed}.",
    "Lapsus vitale": "Quando incassi un colpo hai il {turno.cura_danno.proc:pct} di trasformarne una parte in cura: al danno vengono aggiunti {turno.cura_danno.offset_danno} punti e poi il risultato viene diviso per {turno.cura_danno.divisore} prima di applicare il tuo bonus.",
    "Elsa vitale": "Nel {turno.crescita.proc:pct} dei turni la tua vitalità diventa potere: la crescita usa un decimo dei tuoi HP e metà della tua agilità per calcolare il boost.",
    "Benedizione sanguinolenta": "Nel {turno.cura_danno.proc:pct} dei turni il sangue perso torna utile: trasformi circa metà del danno ricevuto in cura.",
    "Corna da toro": "Nel {turno.terrore.proc:pct} dei turni fai davvero paura: più HP e agilità hai, più il nemico ne risente, usando un decimo dei tuoi HP e un terzo della tua agilità per calcolare il malus.",
    "Sassolino scintillante": "Al momento non applica alcun effetto speciale in combattimento: il Sassolino scintillante è presente tra i gadget, ma non ha ancora una meccanica associata.",
    "Scudo levitante": "Negli assalti aiuti ogni compagno con almeno {assalto.aura.minimo} DEF, oppure con il {assalto.aura.percento_stat:pct} della tua DEF se il risultato è maggiore.",
    "Pegno di amicizia": "Il nemico si trattiene un po': il suo danno scende al {turno.difesa.moltiplicatore_danno:pct_mul} del normale e la tua INT viene usata per renderlo ancora meno efficace.",
    "Cuffia da boia": "Quando il nemico scende a {turno.esecuzione.hp_target_base} HP o meno, non gli lasci il tempo di riprendersi: l'esecuzione lo porta direttamente a {turno.esecuzione.hp_finale} HP.",
    "Veleno del folle": "Ogni attivazione è una scommessa: hai il {turno.veleno.proc:pct} di esplodere di forza e guadagnare {turno.veleno.bonus_dps:signed} danni; se va male, ne perdi {turno.veleno.malus_dps}.",
    "Guanto del falco": "Nel {turno.falcon_punch.proc:pct} dei turni carichi un Falcon Punch che passa quasi sopra l'armatura nemica, trattandone la difesa come se partisse da {turno.falcon_punch.difesa_base}.",
    "Testuggine del vecchio saggio": "Quando il nemico prova a sfruttare la schivata, usi il suo stesso slancio contro di lui e porti il modificatore dell'atterraggio al {turno.atterraggio.moltiplicatore_mod:pct_mul} del normale.",
    "Campanellina concentrante": "Nel {turno.concentrazione.proc:pct} dei turni trovi una concentrazione quasi perfetta: l'agilità sale a {turno.concentrazione.agi}, rendendo il colpo successivo praticamente impossibile da evitare.",
    "Bilanciere": "Nel {turno.bilanciamento.proc:pct} dei turni costringi entrambi a combattere in modo molto più regolare, stringendo il danno attorno a un modificatore di {turno.bilanciamento.mod:x}.",
    "Compasso": "Nel {turno.bilanciamento.proc:pct} dei turni trovi la misura giusta e riduci quasi del tutto gli estremi del danno, portando il riferimento del colpo a {turno.bilanciamento.mod:x}.",
    "Roccia viva": "Nel {turno.golem.proc:pct} dei turni la roccia prende vita e il tuo attacco usa la difesa al posto dell'attacco, aggiungendo anche {turno.golem.bonus_def:signed} difesa al calcolo.",
    "Vincastro": "Quando attacchi hai il {turno.attacco.proc:pct} di trasformare il nemico in una pecorella e schiacciare la sua difesa verso {turno.attacco.difesa_base}; quando difendi hai un altro {turno.difesa.proc:pct} di ridurre il colpo a {turno.difesa.dps} danni.",
    "Fascette luminose": "Dopo una schivata hai il {turno.atterraggio.proc:pct} di rientrare con stile e aggiungere {turno.atterraggio.mod:signed} al modificatore del contrattacco.",
    "Anello d'oro fortissimo": "Fa quello che ci si aspetta da un anello d'oro fortissimo: nelle sfide protegge meglio i tuoi punti quando perdi e rende più ricche le vittorie.",
    "Fantasmino luminoso": "Nel {turno.debuff.proc:pct} dei turni il fantasmino si mette a tormentare il nemico: gli toglie {turno.debuff.agi:abs} agilità e parte da un malus di {turno.debuff.atk_base:abs} attacco e {turno.debuff.def_base:abs} difesa.",
    "Corteccia naturale": "Nel {turno.crescita.proc:pct} dei turni inizi letteralmente a crescere: guadagni {turno.crescita.atk_base:signed} attacco, {turno.crescita.def_base:signed} difesa e {turno.crescita.agi:signed} agilità.",
    "Scudiero fidato": "Nel {turno.blocco.proc:pct} dei turni lo scudiero si mette in mezzo senza pensarci due volte e porta il danno del colpo a {turno.blocco.danno}.",
    "Vasetto all'orlo": "Nel {turno.contrattacco.proc:pct} dei turni il dolore accumulato torna indietro al mittente con una forza casuale tra {turno.contrattacco.random_min:x} e {turno.contrattacco.random_max:x}.",
    "Spuntoni": "Nel {turno.danno_extra.proc:pct} dei turni gli spuntoni trovano il punto giusto e aggiungono {turno.danno_extra.mod:signed} al modificatore del tuo colpo.",
    "Anello di totano": "Nel {turno.cura.proc:pct} dei turni il totano si prende cura di te: recuperi {turno.cura.cura_colpito} HP se vieni colpito e {turno.cura.cura_schivato} HP se schivi; dopo una schivata il contrattacco può anche salire fino a {turno.cura.moltiplicatore_mod_schivato:x}.",
    "Muschio Selvaggio": "Nel {turno.selvaggio.proc:pct} dei turni il muschio potenzia il tuo approccio e ti rende selvaggio, finché non superi i limiti di {turno.selvaggio.limiti_stat.hp} HP, {turno.selvaggio.limiti_stat.atk} attacco, {turno.selvaggio.limiti_stat.def} difesa o {turno.selvaggio.limiti_stat.agi} agilità.",
    "Pozione di furia": "Nel {turno.furia.proc:pct} dei turni la furia prende il sopravvento e guadagni {turno.furia.atk_base:signed} attacco più la tua INT.",
    "Aureola": "Nel {turno.salvezza.proc:pct} dei turni la luce ti protegge e lascia passare solo il {turno.salvezza.moltiplicatore_danno:pct_mul} del danno, quindi ne cancella il {turno.salvezza.moltiplicatore_danno:rid_pct}; almeno {turno.salvezza.danno_min} danno passa comunque.",
    "Ali di luminite": "Nel {turno.volo.proc:pct} dei turni spicchi il volo e porti la tua agilità difensiva a {turno.volo.agi_difesa}, diventando molto più difficile da colpire.",
    "Proteina brullicanti": "Nel {turno.massa.proc:pct} dei turni raddoppi la massa e aggiungi al colpo un altro {turno.massa.moltiplicatore_extra_dps:pct_mul} del suo danno: con il valore attuale il colpo arriva quindi a 2,8× il normale.",
    "Polimerizzazione": "ASSALTO — se indossi Polimerizzazione, ogni altro membro del clan che indossa lo stesso anello ti trasmette il {assalto.polimerizzazione.percento_stat:pct} del proprio ATK, DEF e AGI. Il bonus si somma per ogni portatore e, se usi Portatore di morte, viene moltiplicato per {assalto.polimerizzazione.moltiplicatore_portatore:x}.",
    "Anello della rosa": "Quando vieni colpito hai il {turno.spine.proc:pct} di restituire al nemico {turno.spine.danno} danni fissi.",
    "Anello dei bassi": "Nel {turno.bassi.proc:pct} dei turni i bassi ti attraversano e riducono l'attacco del nemico di {turno.bassi.atk_target:abs}, rendendolo meno pericoloso.",
    "Anello dell'influenza": "Quando entri in combattimento riduci immediatamente gli HP massimi dell'avversario al {turno.influenza.percento_hp:pct} del loro valore originale.",
    "Bastone dello sciamano": "Nel {turno.rigenerazione.proc:pct} dei turni rigeneri {turno.rigenerazione.hp} HP.",
    "Lancia elettrica": "Nel {turno.elettrico.proc:pct} dei turni scarichi una botta elettrica che aggiunge {turno.elettrico.danno} danni al colpo.",
    "Nucleo dell'ira": "Quando vieni colpito guadagni {turno.ira.atk:signed} ATK e {turno.ira.def:signed} DEF; l'effetto si accumula per tutta la sfida.",
    "Mantello dell'ombra": "Quando schivi guadagni {turno.ombra.agi:signed} AGI per il resto della sfida.",
    "Corona del tiranno": "Quando colpisci guadagni {turno.tiranno.atk:signed} ATK per il resto della sfida.",
    "Scudo del martire": "Quando subisci danno curi il tuo avversario di {turno.martire.cura_nemico} HP, ma guadagni {turno.martire.def:signed} DEF per il resto della sfida.",
    "Lama del duellante": "Quando colpisci, il tuo prossimo colpo guadagna {turno.duellante.mod:signed} al modificatore; se manchi, il bonus si azzera.",
    "Occhio del destino": "Nel {turno.destino.proc:pct} dei turni puoi vedere in anticipo se il prossimo attacco andrà a segno e ottieni {turno.destino.agi:signed} AGI.",
    "Cuore del berserker": "Più sei ferito, più colpisci forte: per ogni {turno.berserker.hp_step} HP mancanti guadagni {turno.berserker.atk_per_step:signed} ATK, fino a un massimo di {turno.berserker.max_step} scatti.",
    "Veste del monaco": "Quando subisci un colpo, riduci il danno successivo del {turno.monaco.riduzione:pct}.",
    "Pietra del ritorno": "La prima volta che dovresti morire in una sfida, resti invece a {turno.ritorno.hp} HP.",
    "Maschera del giullare": "All'inizio di ogni turno cambia casualmente uno dei tuoi bonus tra ATK, DEF e AGI.",
    "Catena del carceriere": "Quando colpisci hai il {turno.carceriere.proc:pct} di ridurre l'AGI nemica di {turno.carceriere.agi_target:abs} per il resto della sfida.",
    "Cristallo temporale": "Una volta per sfida, quando subisci un colpo molto pesante, annulli il danno e ripeti il turno.",
    "Sigillo del mercante": "Aumenta del {ricompense.mercante.percento:pct} le monete ottenute dalle vittorie.",
    "Dance Dance Revolution": "Ogni tua schivata consecutiva aumenta la CCCompo di {turno.combo.incremento}; appena non schivi la combo torna a zero. Quando attacchi, ogni punto combo aumenta il danno del {turno.combo.bonus_danno_per_combo_pct:pct}.",
    "GDR semplificato": "Se almeno uno dei due combattenti indossa questo anello, la formula base vale per entrambi: danno = max({turno.formula.danno_min}, ATK - DEF nemica), senza oscillazione casuale. Le schivate e gli effetti successivi continuano a funzionare; i danni ottenuti da questa formula sono marcati con F.",
}
