#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Genera il registro stabile ID -> nomi IT/EN/ES dalle entità della Wiki."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WIKI_DIR = ROOT / "wiki"
REGISTRY_PATH = ROOT / "entities.json"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(WIKI_DIR) not in sys.path:
    sys.path.insert(0, str(WIKI_DIR))

from bootstrap_i18n import (  # noqa: E402
    OfflineTranslator,
    PROTECTED_WORDS,
    apply_glossary,
    translate_many,
)


# Ring, nuclei e scaglioni sono anche oggetti dello zaino: condividono lo
# stesso ID ``item.*`` invece di creare identità parallele.
NAMESPACE = {
    "ring": "item",
    "nucleus": "item",
    "scaglione": "item",
}

NAME_OVERRIDES = {
    "Paladino": {"en": "Paladin", "es": "Paladín"},
    "Drago": {"en": "Dragon", "es": "Dragón"},
    "Pescatore": {"en": "Fisherman", "es": "Pescador"},
    "Pescatore di balene": {"en": "Whale Hunter", "es": "Cazador de ballenas"},
    "Sopravvissuto": {"en": "Survivor", "es": "Superviviente"},
    "Primo impatto": {"en": "First Impact", "es": "Primer impacto"},
    "Gettone arena": {"en": "Arena Token", "es": "Ficha de arena"},
    "Dono stellare": {"en": "Stellar Gift", "es": "Don estelar"},
    "Uno scaglione blu": {"en": "A Blue Tier", "es": "Un nivel azul"},
    "Uno scaglione giallo": {"en": "A Yellow Tier", "es": "Un nivel amarillo"},
    "Uno scaglione nero": {"en": "A Black Tier", "es": "Un nivel negro"},
    "Uno scaglione verde": {"en": "A Green Tier", "es": "Un nivel verde"},
    "NftChallengeBot": {"en": "NftChallengeBot", "es": "NftChallengeBot"},
    "Fanghiglia della palude": {"en": "Swamp Sludge", "es": "Fango del pantano"},
    "Lama del ricercato": {"en": "Outlaw's Blade", "es": "Hoja del forajido"},
    "Spada": {"en": "Sword", "es": "Espada"},
    "Un hp extra": {"en": "One Extra HP", "es": "Un HP extra"},
    "Un machete": {"en": "A Machete", "es": "Un machete"},
    "Macellaio": {"en": "Butcher", "es": "Carnicero"},
    "Macellatore": {"en": "Slaughterer", "es": "Masacrador"},
    "Pioggia": {"en": "Rain", "es": "Lluvia"},
    "Tempesta": {"en": "Storm", "es": "Tormenta"},
    "Normale": {"en": "Normal", "es": "Normal"},
    "Nuvoloso": {"en": "Cloudy", "es": "Nublado"},
    "Arieggiato": {"en": "Breezy", "es": "Ventoso"},
    "Arcobaleno": {"en": "Rainbow", "es": "Arcoíris"},
    "Soleggiato": {"en": "Sunny", "es": "Soleado"},
    "Caldo torrido": {"en": "Scorching Heat", "es": "Calor abrasador"},
    "Caldo infernale": {"en": "Hellish Heat", "es": "Calor infernal"},
    "Nullatenente": {"en": "Penniless", "es": "Indigente"},
}

# Nomi ad alta visibilità revisionati a mano. Il bootstrap automatico resta
# utile per le nuove entità, ma non sovrascrive questa terminologia editoriale.
NAME_OVERRIDES.update({
    # Set
    "Abitante": {"en": "Resident", "es": "Habitante"},
    "Accolito": {"en": "Acolyte", "es": "Acólito"},
    "Accumulatore di meraviglie": {"en": "Wonder Collector", "es": "Coleccionista de maravillas"},
    "Amletico": {"en": "Hamletic", "es": "Hamletiano"},
    "Anima della festa": {"en": "Life of the Party", "es": "Alma de la fiesta"},
    "Anima oscura": {"en": "Dark Soul", "es": "Alma oscura"},
    "Anima persa": {"en": "Lost Soul", "es": "Alma perdida"},
    "Apprendista delle paludi": {"en": "Swamp Apprentice", "es": "Aprendiz del pantano"},
    "Arcidemone": {"en": "Archdemon", "es": "Archidemonio"},
    "Arciere di prima linea": {"en": "Frontline Archer", "es": "Arquero de primera línea"},
    "Armaliere": {"en": "Armorer", "es": "Armero"},
    "Assassino delle ombre": {"en": "Shadow Assassin", "es": "Asesino de las sombras"},
    "Avventuriero delle praterie": {"en": "Grassland Adventurer", "es": "Aventurero de las praderas"},
    "Big Game Hunter": {"en": "Big Game Hunter", "es": "Cazador de caza mayor"},
    "Bug Abuser": {"en": "Bug Abuser", "es": "Abusador de errores"},
    "Cacciatore": {"en": "Hunter", "es": "Cazador"},
    "Cacciatore d'esce": {"en": "Bait Hunter", "es": "Cazador de cebos"},
    "Cacciatore della feccia": {"en": "Scum Hunter", "es": "Cazador de escoria"},
    "Cacciatore di bestie": {"en": "Beast Hunter", "es": "Cazador de bestias"},
    "Cacciatore di uomini": {"en": "Manhunter", "es": "Cazador de hombres"},
    "Campione del sole": {"en": "Champion of the Sun", "es": "Campeón del sol"},
    "Cavaliere d'argento": {"en": "Silver Knight", "es": "Caballero de plata"},
    "Cavaliere del passaggio": {"en": "Knight of the Passage", "es": "Caballero del paso"},
    "Cavaliere delle spine": {"en": "Knight of Thorns", "es": "Caballero de las espinas"},
    "Cecchino modulare": {"en": "Modular Sniper", "es": "Francotirador modular"},
    "Cercatore": {"en": "Seeker", "es": "Buscador"},
    "Cercatore di reliquie": {"en": "Relic Seeker", "es": "Buscador de reliquias"},
    "Chierico": {"en": "Cleric", "es": "Clérigo"},
    "Combattente 2D": {"en": "2D Fighter", "es": "Luchador 2D"},
    "Combattente della taverna": {"en": "Tavern Fighter", "es": "Luchador de taberna"},
    "Combattente diretto": {"en": "Direct Fighter", "es": "Combatiente directo"},
    "Contrabbandiere": {"en": "Smuggler", "es": "Contrabandista"},
    "Controllore del cielo": {"en": "Sky Controller", "es": "Controlador del cielo"},
    "Controllore del'entrata": {"en": "Entrance Controller", "es": "Controlador de la entrada"},
    "Corvo": {"en": "Raven", "es": "Cuervo"},
    "Crociato": {"en": "Crusader", "es": "Cruzado"},
    "Cultista oscuro": {"en": "Dark Cultist", "es": "Cultista oscuro"},
    "Cultista pazzo": {"en": "Mad Cultist", "es": "Cultista loco"},
    "Dannato": {"en": "Damned", "es": "Condenado"},
    "Dannato primordiale": {"en": "Primordial Damned", "es": "Condenado primordial"},
    "Demone delle lame": {"en": "Demon of Blades", "es": "Demonio de las hojas"},
    "Difensore del popolo": {"en": "Defender of the People", "es": "Defensor del pueblo"},
    "Difensore delle mareggiate": {"en": "Storm-Surge Defender", "es": "Defensor de las marejadas"},
    "Disabilitatore provetto": {"en": "Expert Disabler", "es": "Deshabilitador experto"},
    "Dolce mietitore": {"en": "Sweet Reaper", "es": "Dulce segador"},
    "Druido della selva": {"en": "Jungle Druid", "es": "Druida de la selva"},
    "Duellista vermico": {"en": "Worm Duelist", "es": "Duelista vermiforme"},
    "Duro a morire": {"en": "Diehard", "es": "Duro de matar"},
    "Elfo silvano": {"en": "Wood Elf", "es": "Elfo silvano"},
    "Eroe caduto": {"en": "Fallen Hero", "es": "Héroe caído"},
    "Eroe della rivolta": {"en": "Hero of the Uprising", "es": "Héroe de la revuelta"},
    "Esca vivente": {"en": "Living Bait", "es": "Cebo vivo"},
    "Esperto di animali": {"en": "Animal Expert", "es": "Experto en animales"},
    "Eterna sventura": {"en": "Eternal Doom", "es": "Desgracia eterna"},
    "Evocatore del vero potere": {"en": "Summoner of True Power", "es": "Invocador del verdadero poder"},
    "Evocatore delle maree": {"en": "Tide Summoner", "es": "Invocador de las mareas"},
    "Festante oscuro": {"en": "Dark Reveler", "es": "Festejante oscuro"},
    "Fiamma pura": {"en": "Pure Flame", "es": "Llama pura"},
    "Fire lord": {"en": "Fire Lord", "es": "Señor del fuego"},
    "Forma elettro": {"en": "Electro Form", "es": "Forma eléctrica"},
    "Forma fuoco": {"en": "Fire Form", "es": "Forma de fuego"},
    "Forma lunare": {"en": "Lunar Form", "es": "Forma lunar"},
    "Forma terra": {"en": "Earth Form", "es": "Forma terrestre"},
    "Ghoul": {"en": "Ghoul", "es": "Necrófago"},
    "Girarrosto": {"en": "Turnspit", "es": "Asador giratorio"},
    "Giustiziere a V": {"en": "V-Shaped Executioner", "es": "Justiciero en V"},
    "Guardiano del passaggio": {"en": "Guardian of the Passage", "es": "Guardián del paso"},
    "Guardiano della bestie": {"en": "Guardian of Beasts", "es": "Guardián de las bestias"},
    "Guaritore da campo": {"en": "Field Healer", "es": "Sanador de campo"},
    "Guerriero 3D": {"en": "3D Warrior", "es": "Guerrero 3D"},
    "Guerriero Temporale": {"en": "Time Warrior", "es": "Guerrero temporal"},
    "GunSlingher": {"en": "Gunfighter", "es": "Tirador"},
    "Ice and fire": {"en": "Ice and Fire", "es": "Hielo y fuego"},
    "Il comico": {"en": "The Comedian", "es": "El comediante"},
    "Illusionista": {"en": "Illusionist", "es": "Ilusionista"},
    "Incantatore di controparte": {"en": "Counterpart Enchanter", "es": "Encantador de contraparte"},
    "Incubo dei cieli": {"en": "Nightmare of the Skies", "es": "Pesadilla de los cielos"},
    "Inferno risvegliato": {"en": "Awakened Inferno", "es": "Infierno despertado"},
    "Intermezzo": {"en": "Interlude", "es": "Interludio"},
    "Lanciatore olimpico": {"en": "Olympic Thrower", "es": "Lanzador olímpico"},
    "Legionaro di Evelin": {"en": "Evelin's Legionary", "es": "Legionario de Evelin"},
    "Luce persa": {"en": "Lost Light", "es": "Luz perdida"},
    "Lupo di mare": {"en": "Sea Wolf", "es": "Lobo de mar"},
    "Maestro delle tartarughe": {"en": "Turtle Master", "es": "Maestro de las tortugas"},
    "Mago mentale": {"en": "Mind Mage", "es": "Mago mental"},
    "Maledetto": {"en": "Cursed", "es": "Maldito"},
    "Manipolatore di morte": {"en": "Death Manipulator", "es": "Manipulador de la muerte"},
    "Mecha sciamano": {"en": "Mecha Shaman", "es": "Chamán meca"},
    "Medico improvvisato": {"en": "Improvised Medic", "es": "Médico improvisado"},
    "Medievalista": {"en": "Medievalist", "es": "Medievalista"},
    "Mente centrale": {"en": "Central Mind", "es": "Mente central"},
    "Monarca della tempesta di fuoco": {"en": "Firestorm Monarch", "es": "Monarca de la tormenta de fuego"},
    "Monarca oscuro": {"en": "Dark Monarch", "es": "Monarca oscuro"},
    "MusicoSciamano": {"en": "Music Shaman", "es": "Chamán musical"},
    "Neo Genesi": {"en": "Neo Genesis", "es": "Neogénesis"},
    "Nucleo dell'uragano": {"en": "Hurricane Core", "es": "Núcleo del huracán"},
    "Obscurio": {"en": "Obscurio", "es": "Obscurio"},
    "Oltraggioso": {"en": "Outrageous", "es": "Escandaloso"},
    "Ombra silenziosa": {"en": "Silent Shadow", "es": "Sombra silenciosa"},
    "Operatore di classe": {"en": "Class Operator", "es": "Operador de clase"},
    "Oracolo del buio": {"en": "Oracle of Darkness", "es": "Oráculo de la oscuridad"},
    "Orrido": {"en": "Horrid", "es": "Horrendo"},
    "Oscurato": {"en": "Obscured", "es": "Oscurecido"},
    "Pazzo temporale": {"en": "Time Madman", "es": "Loco temporal"},
    "Pazzoide glamour": {"en": "Glamour Freak", "es": "Chiflado glamuroso"},
    "Pescatore alternativo": {"en": "Alternative Fisherman", "es": "Pescador alternativo"},
    "Piarata": {"en": "Pirate", "es": "Pirata"},
    "Piccolo kraken": {"en": "Little Kraken", "es": "Pequeño kraken"},
    "Pilota": {"en": "Pilot", "es": "Piloto"},
    "PiroIncantatore": {"en": "Pyro Enchanter", "es": "Piroencantador"},
    "Portatore di morte": {"en": "Deathbringer", "es": "Portador de la muerte"},
    "Primo al comando": {"en": "First in Command", "es": "Primero al mando"},
    "Primo alla bandiera": {"en": "First to the Flag", "es": "Primero en la bandera"},
    "Primo alla torre": {"en": "First to the Tower", "es": "Primero en la torre"},
    "Proiettile": {"en": "Projectile", "es": "Proyectil"},
    "Pyromante": {"en": "Pyromancer", "es": "Piromante"},
    "Re dei gadget": {"en": "King of Gadgets", "es": "Rey de los gadgets"},
    "Re dei pirati": {"en": "Pirate King", "es": "Rey de los piratas"},
    "Re del raaave": {"en": "King of the Raaave", "es": "Rey del raaave"},
    "Regina golgari": {"en": "Golgari Queen", "es": "Reina golgari"},
    "Ricercatore del pericolo": {"en": "Danger Researcher", "es": "Investigador del peligro"},
    "Rosso D'ossidina": {"en": "Obsidian Red", "es": "Rojo obsidiana"},
    "Sanguinolento": {"en": "Bloodstained", "es": "Sanguinolento"},
    "Sciamano della verità": {"en": "Shaman of Truth", "es": "Chamán de la verdad"},
    "Scudiero del boschetto": {"en": "Squire of the Grove", "es": "Escudero de la arboleda"},
    "Segna ombre": {"en": "Shadow Marker", "es": "Marcador de sombras"},
    "Selvaggio": {"en": "Wild", "es": "Salvaje"},
    "Serial killer": {"en": "Serial Killer", "es": "Asesino en serie"},
    "Shogun moderno": {"en": "Modern Shogun", "es": "Shogun moderno"},
    "Spacca Mostri": {"en": "Monster Smasher", "es": "Aplastamonstruos"},
    "Spaccatesta": {"en": "Headbasher", "es": "Machacacabezas"},
    "Spadaccino Musashi": {"en": "Musashi Swordsman", "es": "Espadachín Musashi"},
    "Survival medievale": {"en": "Medieval Survival", "es": "Supervivencia medieval"},
    "Taglialegna schivo": {"en": "Elusive Lumberjack", "es": "Leñador esquivo"},
    "Teppistello duro": {"en": "Tough Punk", "es": "Matón duro"},
    "Terrore delle ombre": {"en": "Terror of the Shadows", "es": "Terror de las sombras"},
    "Thunderlord": {"en": "Thunderlord", "es": "Señor del trueno"},
    "Tormento di fuoco": {"en": "Fire Torment", "es": "Tormento de fuego"},
    "Uditore del profondo": {"en": "Listener of the Deep", "es": "Oyente de las profundidades"},
    "Ufficiale dell'oltretomba": {"en": "Underworld Officer", "es": "Oficial del inframundo"},
    "Ultima speranza": {"en": "Last Hope", "es": "Última esperanza"},
    "Uomo di classe": {"en": "Classy Man", "es": "Hombre con clase"},
    "Uomo di un tempo": {"en": "Man of Another Time", "es": "Hombre de otra época"},
    "Vampiro": {"en": "Vampire", "es": "Vampiro"},
    "Venere di ferro": {"en": "Iron Venus", "es": "Venus de hierro"},
    "Vigilante": {"en": "Vigilante", "es": "Vigilante"},

    # Stanze e location
    "Armeria": {"en": "Armory", "es": "Armería"},
    "Biblioteca": {"en": "Library", "es": "Biblioteca"},
    "Bisca": {"en": "Gambling Den", "es": "Antro de apuestas"},
    "Boss": {"en": "Boss", "es": "Jefe"},
    "Cancello": {"en": "Gate", "es": "Portón"},
    "Chiesa": {"en": "Church", "es": "Iglesia"},
    "Crepaccio": {"en": "Crevasse", "es": "Grieta"},
    "Cucina": {"en": "Kitchen", "es": "Cocina"},
    "Cunicolo": {"en": "Tunnel", "es": "Túnel"},
    "Distributore": {"en": "Vending Machine", "es": "Máquina expendedora"},
    "Fabbro": {"en": "Blacksmith", "es": "Herrero"},
    "Faro": {"en": "Lighthouse", "es": "Faro"},
    "Fattoria": {"en": "Farm", "es": "Granja"},
    "Fonte magica": {"en": "Magic Spring", "es": "Fuente mágica"},
    "Locanda spettrale": {"en": "Spectral Inn", "es": "Posada espectral"},
    "Luci ed ombre": {"en": "Lights and Shadows", "es": "Luces y sombras"},
    "Lupo solitario": {"en": "Lone Wolf", "es": "Lobo solitario"},
    "Parco": {"en": "Park", "es": "Parque"},
    "Piedistallo": {"en": "Pedestal", "es": "Pedestal"},
    "Pilastri": {"en": "Pillars", "es": "Pilares"},
    "Podio": {"en": "Podium", "es": "Podio"},
    "Sabbie mobili": {"en": "Quicksand", "es": "Arenas movedizas"},
    "Segreta abbandonata": {"en": "Abandoned Dungeon", "es": "Mazmorra abandonada"},
    "Spada conficcata": {"en": "Embedded Sword", "es": "Espada clavada"},
    "Stagno": {"en": "Pond", "es": "Estanque"},
    "Stanza": {"en": "Room", "es": "Sala"},
    "Stanza del sonno": {"en": "Sleeping Chamber", "es": "Cámara del sueño"},
    "Tempio azteco": {"en": "Aztec Temple", "es": "Templo azteca"},
    "Allevamento spettrale": {"en": "Spectral Farm", "es": "Criadero espectral"},
    "Antico deserto": {"en": "Ancient Desert", "es": "Desierto antiguo"},
    "Circolo polare": {"en": "Polar Circle", "es": "Círculo polar"},
    "Città di mezzo": {"en": "Middle City", "es": "Ciudad intermedia"},
    "Delta del fiume Vern": {"en": "Vern River Delta", "es": "Delta del río Vern"},
    "Dune di rione": {"en": "District Dunes", "es": "Dunas del distrito"},
    "Grotte tori": {"en": "Bull Caves", "es": "Cuevas de los toros"},
    "Labirintico inizio": {"en": "Labyrinthine Beginning", "es": "Inicio laberíntico"},
    "Monte cashmere": {"en": "Mount Cashmere", "es": "Monte Cachemira"},
    "Ordine della rocca": {"en": "Order of the Stronghold", "es": "Orden de la fortaleza"},
    "Piana dell'inzio": {"en": "Starting Plain", "es": "Llanura inicial"},
    "Selva dei predatori": {"en": "Predator Jungle", "es": "Selva de los depredadores"},
    "Sentieri spersi": {"en": "Lost Paths", "es": "Senderos perdidos"},

    # Boss, approcci e incantamenti
    "Carl": {"en": "Carl", "es": "Carl"},
    "Cerbero": {"en": "Cerberus", "es": "Cerbero"},
    "Comandante della bastiglia": {"en": "Commander of the Bastille", "es": "Comandante de la Bastilla"},
    "Demone spezza-ossa": {"en": "Bone-Breaker Demon", "es": "Demonio quebrantahuesos"},
    "Fantasma del rimorso": {"en": "Ghost of Remorse", "es": "Fantasma del remordimiento"},
    "Franco est": {"en": "East Franco", "es": "Franco del Este"},
    "IL FOLLE": {"en": "THE MADMAN", "es": "EL LOCO"},
    "IppoSciamano": {"en": "Hippo Shaman", "es": "Hipochamán"},
    "Leviatano delle sabbie": {"en": "Sand Leviathan", "es": "Leviatán de las arenas"},
    "Orrore della palude": {"en": "Swamp Horror", "es": "Horror del pantano"},
    "Pensatore corrotto": {"en": "Corrupted Thinker", "es": "Pensador corrupto"},
    "Balena territoriale": {"en": "Territorial Whale", "es": "Ballena territorial"},
    "Granchio da rave": {"en": "Rave Crab", "es": "Cangrejo de rave"},
    "Kraken Nautico": {"en": "Nautical Kraken", "es": "Kraken náutico"},
    "Aggressivo": {"en": "Aggressive", "es": "Agresivo"},
    "Aggressivo+": {"en": "Aggressive+", "es": "Agresivo+"},
    "Agile": {"en": "Agile", "es": "Ágil"},
    "Agile +": {"en": "Agile +", "es": "Ágil +"},
    "Autorevole": {"en": "Authoritative", "es": "Autoritario"},
    "Conservativo": {"en": "Conservative", "es": "Conservador"},
    "Difensivo": {"en": "Defensive", "es": "Defensivo"},
    "Distaccato": {"en": "Detached", "es": "Distante"},
    "Dragone delle stelle": {"en": "Star Dragon", "es": "Dragón de las estrellas"},
    "Fantamsa del ritorno": {"en": "Ghost of Return", "es": "Fantasma del regreso"},
    "Impavido": {"en": "Fearless", "es": "Intrépido"},
    "Ingannevole": {"en": "Deceptive", "es": "Engañoso"},
    "Malevolo": {"en": "Malevolent", "es": "Malévolo"},
    "OrsoDruido": {"en": "Druid-Bear", "es": "OsoDruida"},
    "Rabbioso": {"en": "Enraged", "es": "Furioso"},
    "Ratto delle tombe": {"en": "Tomb Rat", "es": "Rata de las tumbas"},
    "Rischioso": {"en": "Risky", "es": "Arriesgado"},
    "Schivo": {"en": "Elusive", "es": "Esquivo"},
    "Silvantropo": {"en": "Sylvanthrope", "es": "Silvántropo"},
    "Spavaldo": {"en": "Brash", "es": "Descarado"},
    "Spinto": {"en": "Driven", "es": "Impulsado"},
    "Statico": {"en": "Static", "es": "Estático"},
    "Vendicativo": {"en": "Vengeful", "es": "Vengativo"},
    "Affilatezza": {"en": "Sharpness", "es": "Afilado"},
    "Armadillibilità": {"en": "Armadillo Ability", "es": "Armadillabilidad"},
    "Cangiante": {"en": "Shifting", "es": "Cambiante"},
    "Caricato": {"en": "Charged", "es": "Cargado"},
    "Critico": {"en": "Critical", "es": "Crítico"},
    "Dominio semplice": {"en": "Simple Domain", "es": "Dominio simple"},
    "Duraturo": {"en": "Enduring", "es": "Duradero"},
    "Evocabilità": {"en": "Summonability", "es": "Invocabilidad"},
    "Giallo": {"en": "Yellow", "es": "Amarillo"},
    "Icore": {"en": "Ichor", "es": "Ícor"},
    "Inevitabile": {"en": "Inevitable", "es": "Inevitable"},
    "Ingrossamento": {"en": "Enlargement", "es": "Agrandamiento"},
    "Iridescente": {"en": "Iridescent", "es": "Iridescente"},
    "Legaccio": {"en": "Binding", "es": "Atadura"},
    "Leggiadra": {"en": "Graceful", "es": "Grácil"},
    "Legione": {"en": "Legion", "es": "Legión"},
    "Mimico": {"en": "Mimic", "es": "Mímico"},
    "Minimista": {"en": "Minimalist", "es": "Minimalista"},
    "Multiplo": {"en": "Multiple", "es": "Múltiple"},
    "Onde dell'abisso": {"en": "Waves of the Abyss", "es": "Olas del abismo"},
    "Predominio": {"en": "Dominance", "es": "Predominio"},
    "Smateriabile": {"en": "Dematerializable", "es": "Desmaterializable"},
    "Speranza": {"en": "Hope", "es": "Esperanza"},
    "Spumeggiante": {"en": "Foaming", "es": "Espumoso"},
    "Tocco fantasma": {"en": "Ghost Touch", "es": "Toque fantasmal"},
    "Unione dello spirito": {"en": "Spirit Union", "es": "Unión espiritual"},
    "Urlo di drago": {"en": "Dragon Roar", "es": "Rugido de dragón"},
    "Velenoso": {"en": "Venomous", "es": "Venenoso"},

    # Strutture ed eventi
    "Accampamento": {"en": "Camp", "es": "Campamento"},
    "Bersaglio enorme": {"en": "Huge Target", "es": "Objetivo enorme"},
    "Cane da guardia": {"en": "Guard Dog", "es": "Perro guardián"},
    "Cannoncino": {"en": "Little Cannon", "es": "Cañoncito"},
    "Centrale di cura centralizzata": {"en": "Centralized Healing Center", "es": "Central de curación"},
    "Clone": {"en": "Clone", "es": "Clon"},
    "Fabbro incantaspade": {"en": "Spellblade Smith", "es": "Herrero encantador de espadas"},
    "Muraglione extra": {"en": "Extra Rampart", "es": "Muralla extra"},
    "Sedimento del cucciolo": {"en": "Puppy Sediment", "es": "Sedimento del cachorro"},
    "Spaventapasseri ornamentale": {"en": "Ornamental Scarecrow", "es": "Espantapájaros ornamental"},
    "Spuntone malefico": {"en": "Evil Spike", "es": "Pincho maléfico"},
    "Stazione laser di sicurezza": {"en": "Laser Security Station", "es": "Estación láser de seguridad"},
    "Cyberarena 🤖": {"en": "Cyber Arena 🤖", "es": "Ciberarena 🤖"},
    "Entrata del gungeon 🔫": {"en": "Enter the Gungeon 🔫", "es": "Entrada al Gungeon 🔫"},
    "Eroi della tempesta ⛈": {"en": "Heroes of the Storm ⛈", "es": "Héroes de la tormenta ⛈"},
    "Eroi di altrove 💫": {"en": "Heroes from Elsewhere 💫", "es": "Héroes de otro lugar 💫"},
    "Sopravvivenza zombie 🧟": {"en": "Zombie Survival 🧟", "es": "Supervivencia zombi 🧟"},
    "Fortunello": {"en": "Lucky One", "es": "Afortunado"},
    "Capo del boss": {"en": "Boss of the Boss", "es": "Jefe del jefe"},

    # Obiettivi
    "A metà strada": {"en": "Halfway There", "es": "A medio camino"},
    "A ri vederci": {"en": "See You Again", "es": "Hasta la vista"},
    "Aiuto dungeon": {"en": "Dungeon Helper", "es": "Ayudante de mazmorra"},
    "Andrà meglio la prossima volta": {"en": "Next Time Will Be Better", "es": "La próxima irá mejor"},
    "Bello e bravo": {"en": "Good and Skilled", "es": "Bueno y hábil"},
    "Boss buster": {"en": "Boss Buster", "es": "Cazajefes"},
    "Boss slayer": {"en": "Boss Slayer", "es": "Asesino de jefes"},
    "Caduta con stile": {"en": "Fall with Style", "es": "Caída con estilo"},
    "Campione di sfida": {"en": "Challenge Champion", "es": "Campeón del desafío"},
    "Collezionista": {"en": "Collector", "es": "Coleccionista"},
    "Come non bruciarsi": {"en": "How Not to Get Burned", "es": "Cómo no quemarse"},
    "Danneggiatore": {"en": "Damage Dealer", "es": "Infligidor de daño"},
    "Dito lesto": {"en": "Quick Fingers", "es": "Dedos rápidos"},
    "Forgiatore seriale": {"en": "Serial Smith", "es": "Forjador en serie"},
    "Fra, fatti una vita": {"en": "Bro, Get a Life", "es": "Tío, búscate una vida"},
    "Fuga col sacco": {"en": "Escape with the Loot", "es": "Huida con el botín"},
    "Iperattivo": {"en": "Hyperactive", "es": "Hiperactivo"},
    "Lo vincitor": {"en": "The Winner", "es": "El ganador"},
    "Macro Pescatore": {"en": "Macro Fisherman", "es": "Pescador macro"},
    "Maestro dei boss": {"en": "Boss Master", "es": "Maestro de los jefes"},
    "MEGA aiutino": {"en": "MEGA Little Helper", "es": "Ayudita MEGA"},
    "Micro Pescatore": {"en": "Micro Fisherman", "es": "Pescador micro"},
    "Milano tutta la vita": {"en": "Milan for Life", "es": "Milán de por vida"},
    "Non è andata meglio": {"en": "It Didn't Go Better", "es": "No fue mejor"},
    "Ottima kill": {"en": "Great Kill", "es": "Gran baja"},
    "Perditore": {"en": "Loser", "es": "Perdedor"},
    "Pesca grande ma poco fumo o arrosto": {"en": "Big Catch, Little Smoke or Roast", "es": "Mucha pesca, poco humo o asado"},
    "Precisino": {"en": "Stickler", "es": "Meticuloso"},
    "Prima compera": {"en": "First Purchase", "es": "Primera compra"},
    "Prima scoperta": {"en": "First Discovery", "es": "Primer descubrimiento"},
    "Prima sfida": {"en": "First Challenge", "es": "Primer desafío"},
    "Primo": {"en": "First", "es": "Primero"},
    "Quasi tuto perfetto": {"en": "Almost Everything Perfect", "es": "Casi todo perfecto"},
    "Schiappetta": {"en": "Weakling", "es": "Debilucho"},
    "Set all'improvviso": {"en": "Sudden Set", "es": "Set de repente"},
    "Sfidante tosto": {"en": "Tough Challenger", "es": "Retador duro"},
    "Stessa storia": {"en": "Same Story", "es": "La misma historia"},
    "SUPER SFIDANTE": {"en": "SUPER CHALLENGER", "es": "SÚPER RETADOR"},
    "Super smash sbros sbrau": {"en": "Super Smash Sbros Sbrau", "es": "Super Smash Sbros Sbrau"},
    "Te la sei cercata": {"en": "You Asked for It", "es": "Te lo buscaste"},
    "Titanico": {"en": "Titanic", "es": "Titánico"},
    "Tossico": {"en": "Toxic", "es": "Tóxico"},
    "Tutta fortuna": {"en": "Pure Luck", "es": "Pura suerte"},
    "Ultima a morire": {"en": "Last Woman Standing", "es": "Última en morir"},
    "Ultima kill": {"en": "Last Kill", "es": "Última baja"},
    "Un decimo della collezione": {"en": "A Tenth of the Collection", "es": "Una décima parte de la colección"},
    "Voglioso di perdere": {"en": "Eager to Lose", "es": "Deseoso de perder"},

    # Correzioni lessicali comuni a oggetti e altre entità
    "Armatura maledetta": {"en": "Cursed Armor", "es": "Armadura maldita"},
    "Aureola": {"en": "Halo", "es": "Aureola"},
    "Canna magenta": {"en": "Magenta Rod", "es": "Caña magenta"},
    "cannibale": {"en": "Cannibal", "es": "Caníbal"},
    "Coda-mazza": {"en": "Mace Tail", "es": "Cola de maza"},
    "Copricapo maori": {"en": "Māori Headdress", "es": "Tocado maorí"},
    "cupo": {"en": "Gloomy", "es": "Sombrío"},
    "misterioso": {"en": "Mysterious", "es": "Misterioso"},
    "Ninfea stagnia": {"en": "Stagnant Water Lily", "es": "Nenúfar estancado"},
    "Nulla assoluto": {"en": "Absolute Nothing", "es": "Nada absoluto"},
    "Riverbero": {"en": "Reverberation", "es": "Reverberación"},
    "silenzioso": {"en": "Silent", "es": "Silencioso"},
    "Un pugnale d'oro": {"en": "A Golden Dagger", "es": "Una daga dorada"},
    "vinaccia": {"en": "Pomace", "es": "Orujo"},

    # Nemici
    "Accolito del dolore": {"en": "Acolyte of Pain", "es": "Acólito del dolor"},
    "Artista magico": {"en": "Magic Artist", "es": "Artista mágico"},
    "Assassino delle fronde": {"en": "Frond Assassin", "es": "Asesino de la fronda"},
    "Automa a vapore": {"en": "Steam Automaton", "es": "Autómata de vapor"},
    "Automa massivo": {"en": "Massive Automaton", "es": "Autómata masivo"},
    "Battitore infestato": {"en": "Infested Beater", "es": "Batidor infestado"},
    "Blood maker": {"en": "Blood Maker", "es": "Creador de sangre"},
    "Bomba vivente": {"en": "Living Bomb", "es": "Bomba viviente"},
    "Bruciatore infestata": {"en": "Infested Burner", "es": "Quemador infestado"},
    "Cacciatore di magie": {"en": "Magic Hunter", "es": "Cazador de magia"},
    "Cacciatore versak": {"en": "Versak Hunter", "es": "Cazador versak"},
    "Cammello zombie": {"en": "Zombie Camel", "es": "Camello zombi"},
    "Caricatore inbloccabile": {"en": "Unstoppable Charger", "es": "Cargador imparable"},
    "Crewmate": {"en": "Crewmate", "es": "Tripulante"},
    "Crociato devoto": {"en": "Devout Crusader", "es": "Cruzado devoto"},
    "Crociato impazzito": {"en": "Mad Crusader", "es": "Cruzado enloquecido"},
    "Custode del segreto": {"en": "Keeper of the Secret", "es": "Guardián del secreto"},
    "Demone occhio": {"en": "Eye Demon", "es": "Demonio ocular"},
    "Eleganza": {"en": "Elegance", "es": "Elegancia"},
    "Elfo lunare": {"en": "Moon Elf", "es": "Elfo lunar"},
    "Falena bluastra": {"en": "Bluish Moth", "es": "Polilla azulada"},
    "Folle senziente": {"en": "Sentient Madman", "es": "Loco consciente"},
    "Friggitrice infestata": {"en": "Infested Fryer", "es": "Freidora infestada"},
    "Gorgone": {"en": "Gorgon", "es": "Gorgona"},
    "GuardaDraghi": {"en": "Dragon Watcher", "es": "Guardián de dragones"},
    "Guardiano del ponte": {"en": "Bridge Guardian", "es": "Guardián del puente"},
    "Guardiano della fucina": {"en": "Forge Guardian", "es": "Guardián de la forja"},
    "Guerriero solitario": {"en": "Lone Warrior", "es": "Guerrero solitario"},
    "Immortale": {"en": "Immortal", "es": "Inmortal"},
    "Incuberrimo": {"en": "Supreme Incubus", "es": "Íncubo supremo"},
    "Infimo del sottosuolo": {"en": "Underworld Wretch", "es": "Miserable del subsuelo"},
    "Maialetto Malevolo": {"en": "Malevolent Piglet", "es": "Cerdito malévolo"},
    "Marchiatore": {"en": "Marker", "es": "Marcador"},
    "Matriarca": {"en": "Matriarch", "es": "Matriarca"},
    "Medussa": {"en": "Medusa", "es": "Medusa"},
    "Neutralizzatore": {"en": "Neutralizer", "es": "Neutralizador"},
    "Nobiluomo dello scambio": {"en": "Exchange Nobleman", "es": "Noble del intercambio"},
    "Ombra devastante": {"en": "Devastating Shadow", "es": "Sombra devastadora"},
    "Ombra funesta": {"en": "Ominous Shadow", "es": "Sombra funesta"},
    "Orconte": {"en": "Archon", "es": "Arconte"},
    "Orso druido": {"en": "Druid Bear", "es": "Oso druida"},
    "Patches il Ragno": {"en": "Patches the Spider", "es": "Patches la Araña"},
    "Piarata gorgus": {"en": "Pirate Gorgus", "es": "Pirata Gorgus"},
    "Piarata versak": {"en": "Versak Pirate", "es": "Pirata versak"},
    "Piccolo crociato": {"en": "Little Crusader", "es": "Pequeño cruzado"},
    "Pilota di riserva": {"en": "Reserve Pilot", "es": "Piloto de reserva"},
    "Pipistrello delle taverne": {"en": "Tavern Bat", "es": "Murciélago de taberna"},
    "Pistolero": {"en": "Gunslinger", "es": "Pistolero"},
    "Pollosauro": {"en": "Chicken-Saurus", "es": "Pollosaurio"},
    "Polverello": {"en": "Dustling", "es": "Polvillo"},
    "Ragno della seta": {"en": "Silk Spider", "es": "Araña de seda"},
    "Riccio vorace": {"en": "Voracious Hedgehog", "es": "Erizo voraz"},
    "Sceriffo corrotto": {"en": "Corrupted Sheriff", "es": "Sheriff corrupto"},
    "Sensitivo psitico": {"en": "Psionic Sensitive", "es": "Sensitivo psiónico"},
    "Sergente rinforzato": {"en": "Reinforced Sergeant", "es": "Sargento reforzado"},
    "Sghignoporta": {"en": "Door Grin", "es": "Sonrisa de puerta"},
    "Shogun del mare": {"en": "Shogun of the Sea", "es": "Shogun del mar"},
    "Sopravvissuto zombie": {"en": "Zombie Survivor", "es": "Superviviente zombi"},
    "Spirito di fuoco": {"en": "Fire Spirit", "es": "Espíritu de fuego"},
    "Spirito di terra": {"en": "Earth Spirit", "es": "Espíritu de tierra"},
    "Spirito elettrico": {"en": "Electric Spirit", "es": "Espíritu eléctrico"},
    "Spirito rincorrente": {"en": "Chasing Spirit", "es": "Espíritu perseguidor"},
    "Spirito spaziale": {"en": "Space Spirit", "es": "Espíritu espacial"},
    "Tartartoro": {"en": "Tartarus Bull", "es": "Toro del Tártaro"},
    "Terminatore": {"en": "Terminator", "es": "Terminador"},
    "Tomba cimiteriale": {"en": "Cemetery Tomb", "es": "Tumba del cementerio"},
    "Un abitante del tempio": {"en": "Temple Dweller", "es": "Habitante del templo"},
    "Un golemita": {"en": "A Golemite", "es": "Un golemita"},
    "Un topo gigante": {"en": "A Giant Rat", "es": "Una rata gigante"},
    "Ventilatore infestata": {"en": "Infested Fan", "es": "Ventilador infestado"},
    "Visionario versak": {"en": "Versak Visionary", "es": "Visionario versak"},
    "Vortice di fuoco": {"en": "Fire Vortex", "es": "Vórtice de fuego"},

    # Anelli / gadget (condividono gli ID degli oggetti)
    "Ali di luminite": {"en": "Luminite Wings", "es": "Alas de luminita"},
    "Amuleto del protettore": {"en": "Protector's Amulet", "es": "Amuleto del protector"},
    "Anello d'oro fortissimo": {"en": "Extremely Strong Gold Ring", "es": "Anillo de oro fortísimo"},
    "Anello dei bassi": {"en": "Bass Ring", "es": "Anillo de los bajos"},
    "Anello dell'influenza": {"en": "Ring of Influence", "es": "Anillo de influencia"},
    "Anello dell'occulto": {"en": "Occult Ring", "es": "Anillo de lo oculto"},
    "Anello della rosa": {"en": "Rose Ring", "es": "Anillo de la rosa"},
    "Anello di totano": {"en": "Squid Ring", "es": "Anillo de calamar"},
    "Anello perfezionista": {"en": "Perfectionist Ring", "es": "Anillo perfeccionista"},
    "Anello superfortissimo ma proprio rotto sgravatissimo": {
        "en": "Super-Strong, Totally Broken, Insanely Overpowered Ring",
        "es": "Anillo superfortísimo, totalmente roto y desbalanceado",
    },
    "Aura pessima": {"en": "Terrible Aura", "es": "Aura pésima"},
    "Bastone dello sciamano": {"en": "Shaman's Staff", "es": "Bastón del chamán"},
    "Benedizione sanguinolenta": {"en": "Bloody Blessing", "es": "Bendición sangrienta"},
    "Bilanciere": {"en": "Barbell", "es": "Barra"},
    "Campanellina concentrante": {"en": "Focusing Bell", "es": "Campanilla de concentración"},
    "Carica mobile": {"en": "Mobile Charge", "es": "Carga móvil"},
    "Catena del carceriere": {"en": "Jailer's Chain", "es": "Cadena del carcelero"},
    "Chiavi": {"en": "Keys", "es": "Llaves"},
    "Chiavi dell'aldilà": {"en": "Keys to the Afterlife", "es": "Llaves del más allá"},
    "Cinta del comandante": {"en": "Commander's Belt", "es": "Cinturón del comandante"},
    "Coda demoniaca": {"en": "Demonic Tail", "es": "Cola demoníaca"},
    "Compasso": {"en": "Compass", "es": "Compás"},
    "Corna da toro": {"en": "Bull Horns", "es": "Cuernos de toro"},
    "Corona del tiranno": {"en": "Tyrant's Crown", "es": "Corona del tirano"},
    "Corteccia naturale": {"en": "Natural Bark", "es": "Corteza natural"},
    "Cristallo temporale": {"en": "Time Crystal", "es": "Cristal temporal"},
    "Cuffia da boia": {"en": "Executioner's Hood", "es": "Capucha de verdugo"},
    "Cuore del berserker": {"en": "Berserker's Heart", "es": "Corazón del berserker"},
    "Cuore delle sabbie": {"en": "Heart of the Sands", "es": "Corazón de las arenas"},
    "Dance Dance Revolution": {"en": "Dance Dance Revolution", "es": "Dance Dance Revolution"},
    "Effige della tribe": {"en": "Effigy of the Tribe", "es": "Efigie de la tribu"},
    "Elsa vitale": {"en": "Vital Hilt", "es": "Empuñadura vital"},
    "Fantasmino luminoso": {"en": "Little Light Ghost", "es": "Fantasmita luminoso"},
    "Fascette luminose": {"en": "Glow Bands", "es": "Pulseras luminosas"},
    "GDR semplificato": {"en": "Simplified RPG", "es": "Rol simplificado"},
    "Guanto del falco": {"en": "Hawk Glove", "es": "Guante del halcón"},
    "Guanto titanico": {"en": "Titanic Gauntlet", "es": "Guantelete titánico"},
    "Lama del duellante": {"en": "Duelist's Blade", "es": "Hoja del duelista"},
    "Lancia elettrica": {"en": "Electric Spear", "es": "Lanza eléctrica"},
    "Lapsus vitale": {"en": "Vital Lapse", "es": "Lapsus vital"},
    "Mantello dell'ombra": {"en": "Shadow Cloak", "es": "Manto de la sombra"},
    "Maschera del giullare": {"en": "Jester's Mask", "es": "Máscara del bufón"},
    "Muschio Selvaggio": {"en": "Wild Moss", "es": "Musgo salvaje"},
    "Nucleo dell'ira": {"en": "Core of Wrath", "es": "Núcleo de la ira"},
    "Occhio del destino": {"en": "Eye of Fate", "es": "Ojo del destino"},
    "Occhio del falco": {"en": "Hawk Eye", "es": "Ojo de halcón"},
    "Pegno di amicizia": {"en": "Friendship Token", "es": "Ficha de amistad"},
    "Pietra del ritorno": {"en": "Return Stone", "es": "Piedra de retorno"},
    "Polimerizzazione": {"en": "Polymerization", "es": "Polimerización"},
    "Pozione di furia": {"en": "Fury Potion", "es": "Poción de furia"},
    "Proteina brullicanti": {"en": "Teeming Protein", "es": "Proteína rebosante"},
    "Ricordo straziante": {"en": "Heartbreaking Memory", "es": "Recuerdo desgarrador"},
    "Roccia viva": {"en": "Living Rock", "es": "Roca viva"},
    "Roulette russa": {"en": "Russian Roulette", "es": "Ruleta rusa"},
    "Roulette tibetana": {"en": "Tibetan Roulette", "es": "Ruleta tibetana"},
    "Sasso rotolante": {"en": "Rolling Stone", "es": "Piedra rodante"},
    "Sassolino scintillante": {"en": "Sparkling Pebble", "es": "Guijarro brillante"},
    "Scarica di adrenalina": {"en": "Adrenaline Rush", "es": "Subidón de adrenalina"},
    "Scudiero fidato": {"en": "Trusted Squire", "es": "Escudero fiel"},
    "Scudo del martire": {"en": "Martyr's Shield", "es": "Escudo del mártir"},
    "Scudo levitante": {"en": "Floating Shield", "es": "Escudo flotante"},
    "Sigillo del mercante": {"en": "Merchant's Seal", "es": "Sello del comerciante"},
    "Spuntoni": {"en": "Spikes", "es": "Pinchos"},
    "Stemma del leader": {"en": "Leader's Emblem", "es": "Emblema del líder"},
    "Stemma della rocca": {"en": "Stronghold Emblem", "es": "Emblema de la fortaleza"},
    "Tasto B": {"en": "B Button", "es": "Botón B"},
    "Tasto X": {"en": "X Button", "es": "Botón X"},
    "Testuggine del vecchio saggio": {"en": "Wise Old Man's Tortoise", "es": "Tortuga del viejo sabio"},
    "Un frammento del potere": {"en": "Power Fragment", "es": "Fragmento de poder"},
    "Un generatore incartato": {"en": "Wrapped Generator", "es": "Generador envuelto"},
    "Valvola da 4\"": {"en": "4-Inch Valve", "es": "Válvula de 4 pulgadas"},
    "Vasetto all'orlo": {"en": "Jar Filled to the Brim", "es": "Tarrito hasta el borde"},
    "Veleno del folle": {"en": "Madman's Poison", "es": "Veneno del loco"},
    "Veste del monaco": {"en": "Monk's Robe", "es": "Túnica del monje"},
    "Vincastro": {"en": "Crook", "es": "Cayado"},

    # Oggetti ed equipaggiamenti
    "al neon": {"en": "Neon", "es": "Neón"},
    "Ali piumate": {"en": "Feathered Wings", "es": "Alas emplumadas"},
    "alligatore": {"en": "Alligator", "es": "Caimán"},
    "Anima dispersa": {"en": "Wandering Soul", "es": "Alma errante"},
    "Arco lunghissimo": {"en": "Extra-Long Bow", "es": "Arco larguísimo"},
    "Arco pesante": {"en": "Heavy Bow", "es": "Arco pesado"},
    "Armatura del folle": {"en": "Madman's Armor", "es": "Armadura del loco"},
    "Armatura del macellaio": {"en": "Butcher's Armor", "es": "Armadura del carnicero"},
    "Armatura di carne": {"en": "Flesh Armor", "es": "Armadura de carne"},
    "Armatura di cormorant": {"en": "Cormorant Armor", "es": "Armadura de Cormorant"},
    "Armatura di esche": {"en": "Bait Armor", "es": "Armadura de cebo"},
    "Armatura leggera versak": {"en": "Light Versak Armor", "es": "Armadura ligera versak"},
    "Armatura pesante versak": {"en": "Heavy Versak Armor", "es": "Armadura pesada versak"},
    "Armatura pesantissima": {"en": "Extremely Heavy Armor", "es": "Armadura pesadísima"},
    "Artiglio del mostro": {"en": "Monster Claw", "es": "Garra de monstruo"},
    "Artiglio di Drago": {"en": "Dragon Claw", "es": "Garra de dragón"},
    "Ascia bipenne": {"en": "Double-Bladed Axe", "es": "Hacha bipenne"},
    "Ascia del cacciatore": {"en": "Hunter's Axe", "es": "Hacha del cazador"},
    "Assetto mecha": {"en": "Mecha Rig", "es": "Equipo meca"},
    "Barilotto di birra": {"en": "Beer Keg", "es": "Barril de cerveza"},
    "Bastone del folle": {"en": "Madman's Staff", "es": "Bastón del loco"},
    "Bastone filettato": {"en": "Threaded Rod", "es": "Varilla roscada"},
    "Bastone sferico": {"en": "Spherical Staff", "es": "Bastón esférico"},
    "Benda maledetta": {"en": "Cursed Bandage", "es": "Venda maldita"},
    "Biscotto con scagliette di cioccolato": {"en": "Chocolate-Chip Cookie", "es": "Galleta con pepitas de chocolate"},
    "Blasfemia": {"en": "Blasphemy", "es": "Blasfemia"},
    "Blaster a turbina": {"en": "Turbine Blaster", "es": "Bláster de turbina"},
    "Bomba sneaky": {"en": "Sneaky Bomb", "es": "Bomba sigilosa"},
    "Bussola taumaturgica": {"en": "Thaumaturgic Compass", "es": "Brújula taumatúrgica"},
    "Cacciavite multiuso": {"en": "Multipurpose Screwdriver", "es": "Destornillador multiusos"},
    "Candela blu": {"en": "Blue Candle", "es": "Vela azul"},
    "Canna blu": {"en": "Blue Rod", "es": "Caña azul"},
    "Canna rossa": {"en": "Red Rod", "es": "Caña roja"},
    "Cannoncino carapace": {"en": "Shell Cannon", "es": "Cañoncito caparazón"},
    "Cappa delle selve": {"en": "Woodland Cape", "es": "Capa de la selva"},
    "Cappellino da pescatore": {"en": "Fishing Hat", "es": "Sombrero de pescador"},
    "Cappello messicano": {"en": "Mexican Hat", "es": "Sombrero mexicano"},
    "Catenaccio demoniaco": {"en": "Demonic Bolt", "es": "Cerrojo demoníaco"},
    "Centro temporale": {"en": "Temporal Core", "es": "Núcleo temporal"},
    "Cerficato della nuova ombra": {"en": "Certificate of the New Shadow", "es": "Certificado de la nueva sombra"},
    "Chela animata": {"en": "Animated Claw", "es": "Pinza animada"},
    "Chip elettro": {"en": "Electro Chip", "es": "Chip eléctrico"},
    "Chip fuoco": {"en": "Fire Chip", "es": "Chip de fuego"},
    "Chip lunare": {"en": "Lunar Chip", "es": "Chip lunar"},
    "Chip terra": {"en": "Earth Chip", "es": "Chip terrestre"},
    "Coltelli da lancio": {"en": "Throwing Knives", "es": "Cuchillos arrojadizos"},
    "Conoscenze perdute": {"en": "Lost Knowledge", "es": "Conocimientos perdidos"},
    "Corazza a piastre": {"en": "Plate Armor", "es": "Armadura de placas"},
    "Corazza spuntata": {"en": "Blunt Plate Armor", "es": "Coraza roma"},
    "Corona del rave": {"en": "Rave Crown", "es": "Corona del rave"},
    "Corona maledetta": {"en": "Cursed Crown", "es": "Corona maldita"},
    "Corvo amichevole": {"en": "Friendly Raven", "es": "Cuervo amistoso"},
    "Corvo super bellissimo e fighissima": {"en": "Super-Beautiful, Super-Cool Raven", "es": "Cuervo superhermoso y supergenial"},
    "crack musica": {"en": "Music Crack", "es": "Crack musical"},
    "Critica moderna": {"en": "Modern Critique", "es": "Crítica moderna"},
    "Cronache dirette": {"en": "Direct Chronicles", "es": "Crónicas directas"},
    "del fondale": {"en": "From the Seabed", "es": "Del fondo marino"},
    "Del latte in sacchetto": {"en": "Bagged Milk", "es": "Leche en bolsa"},
    "Del sale estratto dal server": {"en": "Salt Extracted from the Server", "es": "Sal extraída del servidor"},
    "Dell'acqua fresca": {"en": "Fresh Water", "es": "Agua fresca"},
    "Dell'ambrosia": {"en": "Ambrosia", "es": "Ambrosía"},
    "Delle placche metalliche": {"en": "Metal Plates", "es": "Placas metálicas"},
    "delle rive": {"en": "From the Shores", "es": "De las orillas"},
    "Delle squame viscide": {"en": "Slimy Scales", "es": "Escamas viscosas"},
    "Dente infernale": {"en": "Infernal Tooth", "es": "Diente infernal"},
    "Due gemelle luccicanti": {"en": "Two Shiny Twins", "es": "Dos gemelas relucientes"},
    "Elmo d'oro fortissimo": {"en": "Extremely Strong Gold Helmet", "es": "Casco de oro fortísimo"},
    "Fiamma bluastra": {"en": "Bluish Flame", "es": "Llama azulada"},
    "Forcone fiammeggiante": {"en": "Flaming Pitchfork", "es": "Horca llameante"},
    "Foulard dell'ombra": {"en": "Shadow Scarf", "es": "Pañuelo de la sombra"},
    "Frusta di salsiccia": {"en": "Sausage Whip", "es": "Látigo de salchicha"},
    "Frusta telaia": {"en": "Loom Whip", "es": "Látigo de telar"},
    "Fumetto hot degli anni 70": {"en": "Hot 1970s Comic", "es": "Cómic picante de los años 70"},
    "Fuoco purificatore": {"en": "Purifying Fire", "es": "Fuego purificador"},
    "Gigantesco": {"en": "Gigantic", "es": "Gigantesco"},
    "Giubba logora": {"en": "Worn Jacket", "es": "Chaqueta gastada"},
    "Giubbina con lenze": {"en": "Fishing Vest with Lines", "es": "Chaleco con sedales"},
    "Globo magico": {"en": "Magic Globe", "es": "Globo mágico"},
    "Guanti di cormorant": {"en": "Cormorant Gloves", "es": "Guantes de Cormorant"},
    "Guida a piante e veleni": {"en": "Guide to Plants and Poisons", "es": "Guía de plantas y venenos"},
    "Guscio di tartaruga": {"en": "Turtle Shell", "es": "Caparazón de tortuga"},
    "Il ciondolo della creazione": {"en": "Pendant of Creation", "es": "Colgante de la creación"},
    "Il controller del super raggio mortale a neutroni mega pericolosissimo": {
        "en": "Controller for the Super-Deadly, Mega-Dangerous Neutron Beam",
        "es": "Mando del rayo de neutrones supermortal y megapeligroso",
    },
    "Il decino di paperon de' paperoni": {"en": "Scrooge McDuck's Dime", "es": "Moneda de diez centavos de Tío Gilito"},
    "Il re in giallo": {"en": "The King in Yellow", "es": "El Rey de Amarillo"},
    "Junior secondo": {"en": "Junior II", "es": "Junior II"},
    "La spezia": {"en": "The Spice", "es": "La especia"},
    "Lama Mentale": {"en": "Mind Blade", "es": "Hoja mental"},
    "Lama spezzata": {"en": "Broken Blade", "es": "Hoja rota"},
    "Lama temporale": {"en": "Time Blade", "es": "Hoja temporal"},
    "Lancia celeste": {"en": "Celestial Spear", "es": "Lanza celeste"},
    "Laniccio del pantano": {"en": "Swamp Tuft", "es": "Mechón del pantano"},
    "Leggi dello spazio": {"en": "Laws of Space", "es": "Leyes del espacio"},
    "Libro del bene e del male": {"en": "Book of Good and Evil", "es": "Libro del bien y del mal"},
    "Libro della fede": {"en": "Book of Faith", "es": "Libro de la fe"},
    "Libro etereo": {"en": "Ethereal Book", "es": "Libro etéreo"},
    "Mannaia del cacciatore": {"en": "Hunter's Cleaver", "es": "Macheta del cazador"},
    "Mannaia pazza": {"en": "Mad Cleaver", "es": "Macheta loca"},
    "Manto del vampiro": {"en": "Vampire Cloak", "es": "Capa del vampiro"},
    "Mantra dell'aria": {"en": "Air Mantra", "es": "Mantra del aire"},
    "Mazza chiodata": {"en": "Spiked Mace", "es": "Maza con púas"},
    "Mazzuolo acculturato": {"en": "Cultured Mallet", "es": "Mazo culto"},
    "Misture storiche e dove trovarle": {"en": "Historic Brews and Where to Find Them", "es": "Brebajes históricos y dónde encontrarlos"},
    "Nucleo demoniaco instabile": {"en": "Unstable Demonic Core", "es": "Núcleo demoníaco inestable"},
    "Nucleo di bacon instabile": {"en": "Unstable Bacon Core", "es": "Núcleo de beicon inestable"},
    "Nucleo elettrico instabile": {"en": "Unstable Electric Core", "es": "Núcleo eléctrico inestable"},
    "Nucleo marittimo instabile": {"en": "Unstable Marine Core", "es": "Núcleo marino inestable"},
    "Nucleo Necron instabile": {"en": "Unstable Necron Core", "es": "Núcleo Necron inestable"},
    "Nucleo selvaggio instabile": {"en": "Unstable Wild Core", "es": "Núcleo salvaje inestable"},
    "Nucleo terrestre instabile": {"en": "Unstable Earth Core", "es": "Núcleo terrestre inestable"},
    "Nudità incontrastata": {"en": "Unchallenged Nudity", "es": "Desnudez incontestable"},
    "Ordine di leva": {"en": "Draft Order", "es": "Orden de reclutamiento"},
    "Origine della tempesta": {"en": "Origin of the Storm", "es": "Origen de la tormenta"},
    "palla": {"en": "Ball", "es": "Bola"},
    "Palla chiodata": {"en": "Spiked Ball", "es": "Bola con púas"},
    "Palla Ombra": {"en": "Shadow Ball", "es": "Bola sombra"},
    "Pergamena del potere": {"en": "Power Scroll", "es": "Pergamino de poder"},
    "Pessime idee": {"en": "Terrible Ideas", "es": "Ideas pésimas"},
    "Picca di diamante": {"en": "Diamond Pike", "es": "Pica de diamante"},
    "Pistola del west": {"en": "Western Pistol", "es": "Pistola del oeste"},
    "Piuma celeste": {"en": "Celestial Feather", "es": "Pluma celeste"},
    "Piuma vulcanica": {"en": "Volcanic Feather", "es": "Pluma volcánica"},
    "Protezione della beta": {"en": "Beta Protection", "es": "Protección beta"},
    "Pugnale del vampiro": {"en": "Vampire Dagger", "es": "Daga del vampiro"},
    "Raccolta del deserto": {"en": "Desert Collection", "es": "Colección del desierto"},
    "Racconti e terrori del nord": {"en": "Tales and Terrors of the North", "es": "Relatos y terrores del norte"},
    "Radice vitale": {"en": "Vital Root", "es": "Raíz vital"},
    "Roccia incisa": {"en": "Engraved Rock", "es": "Roca grabada"},
    "Runa malconcia": {"en": "Worn Rune", "es": "Runa maltrecha"},
    "Sacco da cadaveri": {"en": "Body Bag", "es": "Bolsa para cadáveres"},
    "Salmonato": {"en": "Salmon-Colored", "es": "Color salmón"},
    "Scaglie di Drago": {"en": "Dragon Scales", "es": "Escamas de dragón"},
    "Scaglioni pesanti": {"en": "Heavy Tiers", "es": "Escalones pesados"},
    "Scritto sulle luci": {"en": "Written in the Lights", "es": "Escrito en las luces"},
    "Scudo con cose attaccate": {"en": "Shield with Stuff Attached", "es": "Escudo con cosas pegadas"},
    "Scudo d'ossidiana": {"en": "Obsidian Shield", "es": "Escudo de obsidiana"},
    "Scudo del comandante": {"en": "Commander's Shield", "es": "Escudo del comandante"},
    "Scudo del paladino": {"en": "Paladin's Shield", "es": "Escudo del paladín"},
    "Scudo spinato": {"en": "Spiked Shield", "es": "Escudo con púas"},
    "Secchiello di vermi": {"en": "Bucket of Worms", "es": "Cubo de gusanos"},
    "Secchio di ferro": {"en": "Iron Bucket", "es": "Cubo de hierro"},
    "Sgabello da bar": {"en": "Bar Stool", "es": "Taburete de bar"},
    "Spada a protoni": {"en": "Proton Sword", "es": "Espada de protones"},
    "Spada corta": {"en": "Short Sword", "es": "Espada corta"},
    "Spada d'oro fortissima": {"en": "Extremely Strong Gold Sword", "es": "Espada de oro fortísima"},
    "Spada del crociato": {"en": "Crusader's Sword", "es": "Espada del cruzado"},
    "Spada del dio della fucina": {"en": "Sword of the Forge God", "es": "Espada del dios de la forja"},
    "Spada della beta": {"en": "Beta Sword", "es": "Espada beta"},
    "Spada della vitalità": {"en": "Sword of Vitality", "es": "Espada de la vitalidad"},
    "Spada delle fiamme": {"en": "Flame Sword", "es": "Espada de las llamas"},
    "Spada di sangue di demone": {"en": "Demon-Blood Sword", "es": "Espada de sangre demoníaca"},
    "Spada lunga quanto serve": {"en": "Just-Long-Enough Sword", "es": "Espada todo lo larga que hace falta"},
    "Spina insanguinata": {"en": "Bloody Thorn", "es": "Espina ensangrentada"},
    "spinato": {"en": "Barbed", "es": "Espinoso"},
    "Staffa da rave": {"en": "Rave Stirrup", "es": "Estribo de rave"},
    "Stampa guerrigliera": {"en": "Guerrilla Print", "es": "Estampa guerrillera"},
    "Stecca di ferro": {"en": "Iron Bar", "es": "Barra de hierro"},
    "Stecca tori": {"en": "Bull Bar", "es": "Barra de toro"},
    "Stendardo del crociato": {"en": "Crusader's Banner", "es": "Estandarte del cruzado"},
    "Stocco magico": {"en": "Magic Rapier", "es": "Estoque mágico"},
    "Tavole della legge": {"en": "Tablets of the Law", "es": "Tablas de la ley"},
    "Tavoletta antica": {"en": "Ancient Tablet", "es": "Tablilla antigua"},
    "Tentacolo viscido": {"en": "Slimy Tentacle", "es": "Tentáculo viscoso"},
    "Teschio d'ossidiana": {"en": "Obsidian Skull", "es": "Calavera de obsidiana"},
    "The mask: Il libro": {"en": "The Mask: The Book", "es": "La máscara: El libro"},
    "Totem spirituale": {"en": "Spiritual Totem", "es": "Tótem espiritual"},
    "Ultimo barlore": {"en": "Last Glimmer", "es": "Último destello"},
    "Un armatura in filo spinato": {"en": "A Suit of Barbed-Wire Armor", "es": "Una armadura de alambre de púas"},
    "Un biglietto polivalente": {"en": "A Multipurpose Ticket", "es": "Un billete multiusos"},
    "un castoro cattivissimo": {"en": "A Very Mean Beaver", "es": "Un castor malísimo"},
    "Un copricapo rossastro": {"en": "A Reddish Headdress", "es": "Un tocado rojizo"},
    "Un dente di kraken": {"en": "A Kraken Tooth", "es": "Un diente de kraken"},
    "Un doblone verde fluo in plutonio": {"en": "A Fluorescent Green Plutonium Doubloon", "es": "Un doblón verde fluorescente de plutonio"},
    "Un eco-locatore": {"en": "An Echo Locator", "es": "Un ecolocalizador"},
    "Un fucile a pallettoni": {"en": "A Shotgun", "es": "Una escopeta"},
    "Un fune di fuga": {"en": "An Escape Rope", "es": "Una cuerda de escape"},
    "Un idoletto": {"en": "A Small Idol", "es": "Un idolito"},
    "Un libro su tutte le creature": {"en": "A Book About Every Creature", "es": "Un libro sobre todas las criaturas"},
    "Un manganello": {"en": "A Truncheon", "es": "Una porra"},
    "Un mantello nero cenere": {"en": "An Ash-Black Cloak", "es": "Una capa negro ceniza"},
    "Un megafono megaenorme": {"en": "A Mega-Huge Megaphone", "es": "Un megáfono megagigante"},
    "Un oggetto incartato": {"en": "A Wrapped Item", "es": "Un objeto envuelto"},
    "Un piccolo uccellino scheletrico": {"en": "A Small Skeletal Bird", "es": "Un pequeño pájaro esquelético"},
    "Un pompa del nonno": {"en": "Grandpa's Pump", "es": "La bomba del abuelo"},
    "Un punto agilità": {"en": "One Agility Point", "es": "Un punto de agilidad"},
    "Un punto attacco": {"en": "One Attack Point", "es": "Un punto de ataque"},
    "Un punto difesa": {"en": "One Defense Point", "es": "Un punto de defensa"},
    "Un rolex oro": {"en": "A Gold Rolex", "es": "Un Rolex de oro"},
    "Un tavolo speziato": {"en": "A Spiced Table", "es": "Una mesa especiada"},
    "Un terzo occhio": {"en": "A Third Eye", "es": "Un tercer ojo"},
    "Un teschio antico": {"en": "An Ancient Skull", "es": "Una calavera antigua"},
    "Un visore laser": {"en": "A Laser Visor", "es": "Un visor láser"},
    "Una balestra d'oro": {"en": "A Golden Crossbow", "es": "Una ballesta de oro"},
    "Una bandana da tipo tosto": {"en": "A Tough-Guy Bandana", "es": "Una bandana de tipo duro"},
    "Una bibbia inversa": {"en": "An Inverted Bible", "es": "Una biblia inversa"},
    "Una chitarra acustica": {"en": "An Acoustic Guitar", "es": "Una guitarra acústica"},
    "Una copia dell'arte della guerra autografata": {"en": "A Signed Copy of The Art of War", "es": "Una copia firmada de El arte de la guerra"},
    "Una falce spaventosa": {"en": "A Terrifying Scythe", "es": "Una guadaña aterradora"},
    "Una katana ben affilata": {"en": "A Well-Sharpened Katana", "es": "Una katana bien afilada"},
    "Una licenza per animali domestici": {"en": "A Pet License", "es": "Una licencia para mascotas"},
    "Una mail di spam con anche qualche pene": {"en": "A Spam Email with a Few Dicks Too", "es": "Un correo de spam con algún que otro pene"},
    "Una maschera da sub beta tester": {"en": "A Beta-Tester Diving Mask", "es": "Una máscara de buceo de beta tester"},
    "Una mazza ferrata": {"en": "A Spiked Mace", "es": "Una maza con púas"},
    "Una spilla rossa": {"en": "A Red Pin", "es": "Un pin rojo"},
    "Una targhetta da 100 iscritti": {"en": "A 100-Subscriber Plaque", "es": "Una placa de 100 suscriptores"},
    "Una teca di biscotti": {"en": "A Cookie Display Case", "es": "Una vitrina de galletas"},
    "Una tempesta in barattolo": {"en": "A Storm in a Jar", "es": "Una tormenta en un frasco"},
    "Una tortina di compleanno alla fragola, ciliegia, totano, banana, pandispagna, mirto, marzapane e altre cose così": {
        "en": "A Little Birthday Cake with Strawberry, Cherry, Squid, Banana, Sponge Cake, Myrtle, Marzipan, and Stuff Like That",
        "es": "Una tartita de cumpleaños de fresa, cereza, calamar, plátano, bizcocho, mirto, mazapán y cosas así",
    },
    "Una valigia senza fine": {"en": "An Endless Suitcase", "es": "Una maleta sin fin"},
    "Una ventolina leddissima": {"en": "An Ultra-LED Fan", "es": "Un ventilador llenísimo de LED"},
    "Una ventolina velocissima": {"en": "A Super-Fast Fan", "es": "Un ventilador rapidísimo"},
    "Uncino da piarata": {"en": "Pirate Hook", "es": "Garfio de pirata"},
    "Uncino enorme": {"en": "Huge Hook", "es": "Garfio enorme"},
    "Uncino rituale": {"en": "Ritual Hook", "es": "Garfio ritual"},
    "Uno scudo d'oro": {"en": "A Golden Shield", "es": "Un escudo dorado"},
    "Uno smoking elegante": {"en": "An Elegant Tuxedo", "es": "Un esmoquin elegante"},
    "Uno stimpak": {"en": "A Stimpak", "es": "Un stimpak"},
    "Unto e lercio": {"en": "Greasy and Filthy", "es": "Grasiento y mugriento"},
    "Vanga da cimitero": {"en": "Cemetery Shovel", "es": "Pala de cementerio"},
    "Velo di catena": {"en": "Chain Veil", "es": "Velo de cadenas"},
    "Yoga estremo per persone comuni ma non troppo": {"en": "Extreme Yoga for Ordinary—but Not Too Ordinary—People", "es": "Yoga extremo para gente común, pero no demasiado"},
    "Zanna del aliena": {"en": "Alien Fang", "es": "Colmillo alienígena"},
    "Zanna maledetta": {"en": "Cursed Fang", "es": "Colmillo maldito"},
})

# Ingredienti e scelte sono testi brevi e spesso volutamente surreali: una
# terminologia esplicita evita che il modello li interpreti fuori contesto.
NAME_OVERRIDES.update({
    # Ingredienti
    "Melograno": {"en": "Pomegranate", "es": "Granada"},
    "Ambra": {"en": "Amber", "es": "Ámbar"},
    "Frammento di coso blu": {"en": "Blue Thingamajig Fragment", "es": "Fragmento de cachivache azul"},
    "Frammento di coso giallo": {"en": "Yellow Thingamajig Fragment", "es": "Fragmento de cachivache amarillo"},
    "Frammento di coso verde": {"en": "Green Thingamajig Fragment", "es": "Fragmento de cachivache verde"},
    "Lapidina": {"en": "Lapidina", "es": "Lapidina"},
    "Sasso buffo": {"en": "Funny Rock", "es": "Piedra graciosa"},
    "Fungo a pois": {"en": "Polka-Dot Mushroom", "es": "Hongo de lunares"},
    "Piuma di struzzo": {"en": "Ostrich Feather", "es": "Pluma de avestruz"},
    "Piuma di pavone": {"en": "Peacock Feather", "es": "Pluma de pavo real"},
    "Piumone": {"en": "Duvet", "es": "Edredón"},
    "Erba cristallina": {"en": "Crystalline Herb", "es": "Hierba cristalina"},
    "Erba di luna": {"en": "Moon Herb", "es": "Hierba lunar"},
    "Foglietto di carta": {"en": "Scrap of Paper", "es": "Papelito"},
    "Verme ancora vivo": {"en": "Still-Living Worm", "es": "Gusano todavía vivo"},
    "Osso di cane": {"en": "Dog Bone", "es": "Hueso de perro"},
    "Teschio di coniglio": {"en": "Rabbit Skull", "es": "Cráneo de conejo"},
    "Elemento instabile": {"en": "Unstable Element", "es": "Elemento inestable"},
    "Polvere": {"en": "Dust", "es": "Polvo"},
    "Un coccio di vetro": {"en": "A Glass Shard", "es": "Un fragmento de vidrio"},
    "Un coccio di smeraldo": {"en": "An Emerald Shard", "es": "Un fragmento de esmeralda"},
    "Un elettrolite": {"en": "An Electrolyte", "es": "Un electrolito"},
    "Una foglia di pino": {"en": "A Pine Needle", "es": "Una hoja de pino"},
    "Un ago di salice": {"en": "A Willow Needle", "es": "Una aguja de sauce"},
    "Una pera": {"en": "A Pear", "es": "Una pera"},
    "Una mela succosa": {"en": "A Juicy Apple", "es": "Una manzana jugosa"},
    "Una talpa": {"en": "A Mole", "es": "Un topo"},
    "Un capello umano": {"en": "A Human Hair", "es": "Un cabello humano"},
    "Del latte": {"en": "Some Milk", "es": "Un poco de leche"},
    "Un crisantemo orripilante": {"en": "A Horrifying Chrysanthemum", "es": "Un crisantemo horripilante"},
    "Un giglio": {"en": "A Lily", "es": "Un lirio"},
    "Del sangue": {"en": "Some Blood", "es": "Un poco de sangre"},
    "Un ala di pipistrello": {"en": "A Bat Wing", "es": "Un ala de murciélago"},
    "Un pennello": {"en": "A Paintbrush", "es": "Un pincel"},
    "Del liquame": {"en": "Some Slurry", "es": "Un poco de purín"},
    "Delle bacche rosse": {"en": "Some Red Berries", "es": "Unas bayas rojas"},
    "Il pendente di una giovane": {"en": "A Young Woman's Pendant", "es": "El colgante de una joven"},
    "Un piccolo soffione": {"en": "A Small Dandelion", "es": "Un pequeño diente de león"},
    "Un albicocca": {"en": "An Apricot", "es": "Un albaricoque"},
    "Un vero artiglio di drago": {"en": "A Real Dragon Claw", "es": "Una auténtica garra de dragón"},
    "Un frammento di cosacca": {"en": "A Cossack Fragment", "es": "Un fragmento de cosaca"},

    # Scelte sceniche / pulsanti
    "Non ora": {"en": "Not Now", "es": "Ahora no"},
    "Estrai la spada": {"en": "Draw the Sword", "es": "Desenvaina la espada"},
    "Un mattone ancestrale": {"en": "An Ancestral Brick", "es": "Un ladrillo ancestral"},
    "Una piuma azteca": {"en": "An Aztec Feather", "es": "Una pluma azteca"},
    "Un cappello da esploratore": {"en": "An Explorer's Hat", "es": "Un sombrero de explorador"},
    "Bevi": {"en": "Drink", "es": "Bebe"},
    "Passa": {"en": "Move On", "es": "Sigue adelante"},
    "Gira per la locanda": {"en": "Wander Around the Inn", "es": "Recorre la posada"},
    "Corri via": {"en": "Run Away", "es": "Huye"},
    "Immergitici": {"en": "Dive In", "es": "Sumérgete"},
    "Ti ci avvicini": {"en": "Go Near It", "es": "Te acercas a eso"},
    "Fuggi!": {"en": "Run!", "es": "¡Huye!"},
    "Nutri le mucche": {"en": "Feed the Cows", "es": "Alimenta a las vacas"},
    "Mungi le mucche": {"en": "Milk the Cows", "es": "Ordeña las vacas"},
    "Subito": {"en": "Right Away", "es": "Ahora mismo"},
    "Nah": {"en": "Nah", "es": "Nah"},
    "Passo": {"en": "I'll Pass", "es": "Paso"},
    "Ne prendo una": {"en": "I'll Take One", "es": "Me llevo una"},
    "Ne prendo 5": {"en": "I'll Take 5", "es": "Me llevo 5"},
    "Ne prendo 10": {"en": "I'll Take 10", "es": "Me llevo 10"},
    "Prendo il tavolo intero": {"en": "I'll Take the Whole Table", "es": "Me llevo toda la mesa"},
    "Tocchi la crepa": {"en": "Touch the Crack", "es": "Toca la grieta"},
    "Ti allontani": {"en": "Step Away", "es": "Te alejas"},
    "Avvicinati": {"en": "Move Closer", "es": "Acércate"},
    "Allontanati": {"en": "Move Away", "es": "Aléjate"},
    "Approcciala": {"en": "Approach Her", "es": "Acércate a ella"},
    "Disco acuminato": {"en": "Sharp Disc", "es": "Disco afilado"},
    "Disco ricurvo": {"en": "Curved Disc", "es": "Disco curvo"},
    "Disco bilanciato": {"en": "Balanced Disc", "es": "Disco equilibrado"},
    "Peschiamo!": {"en": "Let's Fish!", "es": "¡Vamos a pescar!"},
    "Non è il caso": {"en": "Better Not", "es": "Mejor no"},
    "Fuggi": {"en": "Flee", "es": "Huir"},
    "Fermali": {"en": "Stop Them", "es": "Detenlos"},
    "Parlaci": {"en": "Talk to Them", "es": "Habla con ellos"},
    "Entraci": {"en": "Go Inside", "es": "Entra"},
    "Ignorala": {"en": "Ignore Her", "es": "Ignórala"},
    "Svegliati": {"en": "Wake Up", "es": "Despierta"},
    "Affronta": {"en": "Face It", "es": "Enfréntalo"},
    "Prega": {"en": "Pray", "es": "Reza"},
    "Ritirati": {"en": "Retreat", "es": "Retírate"},
    "Metti monetina": {"en": "Insert a Coin", "es": "Inserta una moneda"},
    "Anche no": {"en": "Absolutely Not", "es": "Ni hablar"},
    "Scommetti": {"en": "Bet", "es": "Apuesta"},
    "N'altra volta": {"en": "Another Time", "es": "En otra ocasión"},
    "Sali": {"en": "Go Up", "es": "Sube"},
    "Scendi": {"en": "Go Down", "es": "Baja"},
    "Non cliccare": {"en": "Don't Click", "es": "No hagas clic"},
    "Vedere": {"en": "See", "es": "Ver"},
    "Essere visto": {"en": "Be Seen", "es": "Ser visto"},
    "1° posto": {"en": "1st Place", "es": "1.er puesto"},
    "2° posto": {"en": "2nd Place", "es": "2.º puesto"},
    "3° posto": {"en": "3rd Place", "es": "3.er puesto"},
})

# I pet conservano il tono assurdo degli originali e le emoji fanno parte del
# nome visualizzato, quindi sono revisionati esplicitamente.
NAME_OVERRIDES.update({
    "Una bottiglia di birra senza schiuma 🍺": {"en": "A Foamless Bottle of Beer 🍺", "es": "Una botella de cerveza sin espuma 🍺"},
    "Un pupazzo di neve sciolto ⛄️": {"en": "A Melted Snowman ⛄️", "es": "Un muñeco de nieve derretido ⛄️"},
    "Un intera barca ⛵️": {"en": "An Entire Boat ⛵️", "es": "Un barco entero ⛵️"},
    "un loot bug 🐛": {"en": "A Loot Bug 🐛", "es": "Un bicho de botín 🐛"},
    "ewqfk jpoqewk k+564➿": {"en": "ewqfk jpoqewk k+564➿", "es": "ewqfk jpoqewk k+564➿"},
    "Una giraffa nana 🦒": {"en": "A Dwarf Giraffe 🦒", "es": "Una jirafa enana 🦒"},
    "Un efelante 🐘": {"en": "An Efelant 🐘", "es": "Un efelante 🐘"},
    "Un orrore del passaggio 🧿": {"en": "A Horror of the Passage 🧿", "es": "Un horror del pasaje 🧿"},
    "Un estintore scarico senziente 🧯": {"en": "A Sentient Empty Fire Extinguisher 🧯", "es": "Un extintor descargado consciente 🧯"},
    "Un satellite spia 🛰️": {"en": "A Spy Satellite 🛰️", "es": "Un satélite espía 🛰️"},
    "Un cervello fluttuante🧠": {"en": "A Floating Brain 🧠", "es": "Un cerebro flotante 🧠"},
    "Internet 🌐": {"en": "The Internet 🌐", "es": "Internet 🌐"},
    "Un trasformers non trasformabile 🚁": {"en": "A Non-Transforming Transformer 🚁", "es": "Un Transformer que no se transforma 🚁"},
    "Un flamingo rosa da giardino 🦩": {"en": "A Pink Garden Flamingo 🦩", "es": "Un flamenco rosa de jardín 🦩"},
    "Un tacchino farcito 🦃": {"en": "A Stuffed Turkey 🦃", "es": "Un pavo relleno 🦃"},
    "Una formica in scala 1:1 🐜": {"en": "A Life-Size Ant 🐜", "es": "Una hormiga a escala 1:1 🐜"},
    "Un fatino 🧚": {"en": "A Little Fairy 🧚", "es": "Un hada diminuta 🧚"},
    "Teddy bear 🧸": {"en": "Teddy Bear 🧸", "es": "Osito de peluche 🧸"},
    "Un funghetto allucinogeno 🍄": {"en": "A Little Hallucinogenic Mushroom 🍄", "es": "Un honguito alucinógeno 🍄"},
    "Piedino 🦕": {"en": "Littlefoot 🦕", "es": "Piecito 🦕"},
    "Un teschio umano volante ☠️": {"en": "A Flying Human Skull ☠️", "es": "Un cráneo humano volador ☠️"},
    "Un cashellino 🏰": {"en": "A Little Cashellino 🏰", "es": "Un pequeño Cashellino 🏰"},
    "Un re del kubb 👑": {"en": "A King of Kubb 👑", "es": "Un rey del kubb 👑"},
    "Un tecnico improvvisato🔧": {"en": "An Improvised Technician 🔧", "es": "Un técnico improvisado 🔧"},
    "Thorgi 🐶🔨": {"en": "Thorgi 🐶🔨", "es": "Thorgi 🐶🔨"},
    "Un sasso domestico 🪨": {"en": "A Pet Rock 🪨", "es": "Una piedra mascota 🪨"},
    "Un aquilotto 🦅": {"en": "An Eaglet 🦅", "es": "Un aguilucho 🦅"},
    "Una papera 🦆": {"en": "A Duck 🦆", "es": "Un pato 🦆"},
    "Un oca fastidiosa 🦢": {"en": "An Annoying Goose 🦢", "es": "Un ganso molesto 🦢"},
    "Un piccione 🐦": {"en": "A Pigeon 🐦", "es": "Una paloma 🐦"},
    "Un pollo da combattimento🐓": {"en": "A Fighting Chicken 🐓", "es": "Un pollo de combate 🐓"},
    "Un rinoceronte🦏": {"en": "A Rhinoceros 🦏", "es": "Un rinoceronte 🦏"},
    "Una mucca pascolante 🐄": {"en": "A Grazing Cow 🐄", "es": "Una vaca pastando 🐄"},
    "Un cinghialetto da assedio🐗": {"en": "A Siege Boarlet 🐗", "es": "Un jabato de asedio 🐗"},
    "Un cinghialetto cavalcabile🐗": {"en": "A Rideable Boarlet 🐗", "es": "Un jabato montable 🐗"},
    "Un cervo 🦌": {"en": "A Deer 🦌", "es": "Un ciervo 🦌"},
    "Una zebra a pois 🦓": {"en": "A Polka-Dot Zebra 🦓", "es": "Una cebra de lunares 🦓"},
    "Un unicorno 🦄": {"en": "A Unicorn 🦄", "es": "Un unicornio 🦄"},
    "Un asinello da soma🐴": {"en": "A Pack Donkey 🐴", "es": "Un burro de carga 🐴"},
    "Un cosplayer dell'uomo tigre 🐯": {"en": "A Tiger Man Cosplayer 🐯", "es": "Un cosplayer del Hombre Tigre 🐯"},
    "Un giovane leone 🦁": {"en": "A Young Lion 🦁", "es": "Un león joven 🦁"},
    "Una tigre bengalese 🐅": {"en": "A Bengal Tiger 🐅", "es": "Un tigre de Bengala 🐅"},
    "Una lontra a londra 🦦": {"en": "An Otter in London 🦦", "es": "Una nutria en Londres 🦦"},
    "Un ippopotamo 🦛": {"en": "A Hippopotamus 🦛", "es": "Un hipopótamo 🦛"},
    "Un ratto portatore di peste🐀": {"en": "A Plague-Bearing Rat 🐀", "es": "Una rata portadora de la peste 🐀"},
    "Una ratto di fogna 🐀": {"en": "A Sewer Rat 🐀", "es": "Una rata de alcantarilla 🐀"},
    "Un gattino polidimensionale 🐈": {"en": "A Multidimensional Kitten 🐈", "es": "Un gatito multidimensional 🐈"},
    "Una volpe 🦊": {"en": "A Fox 🦊", "es": "Un zorro 🦊"},
    "Un orsetto lavatore 🦝": {"en": "A Raccoon 🦝", "es": "Un mapache 🦝"},
    "Un lupo montano 🐺": {"en": "A Mountain Wolf 🐺", "es": "Un lobo de montaña 🐺"},
    "Un mastino 🐕": {"en": "A Mastiff 🐕", "es": "Un mastín 🐕"},
    "Un tasso 🦡": {"en": "A Badger 🦡", "es": "Un tejón 🦡"},
    "Un porchetto sardo 🐖": {"en": "A Little Sardinian Pig 🐖", "es": "Un cerdito sardo 🐖"},
    "Un maialino coraggioso 🐖": {"en": "A Brave Piglet 🐖", "es": "Un cerdito valiente 🐖"},
    "King kong nano 🦍": {"en": "Dwarf King Kong 🦍", "es": "King Kong enano 🦍"},
    "Un pappagallo ripetitore🦜": {"en": "A Repeating Parrot 🦜", "es": "Un loro repetidor 🦜"},
    "Un pappagallo coloratissimo 🦜": {"en": "An Incredibly Colorful Parrot 🦜", "es": "Un loro supercolorido 🦜"},
    "Un coccodrillo🐊": {"en": "A Crocodile 🐊", "es": "Un cocodrilo 🐊"},
    "Una tartaruga alligatore 🐢": {"en": "An Alligator Snapping Turtle 🐢", "es": "Una tortuga caimán 🐢"},
    "Una tartaruga dei 5 mari🐢": {"en": "A Turtle of the Five Seas 🐢", "es": "Una tortuga de los cinco mares 🐢"},
    "Un camaleonte 🦎": {"en": "A Chameleon 🦎", "es": "Un camaleón 🦎"},
    "Pasce, il pesce volante 🐟": {"en": "Pasce, the Flying Fish 🐟", "es": "Pasce, el pez volador 🐟"},
    "Un cucciolo di drago🐲": {"en": "A Dragon Hatchling 🐲", "es": "Una cría de dragón 🐲"},
    "Un gufo notturno 🦉": {"en": "A Night Owl 🦉", "es": "Un búho nocturno 🦉"},
    "Uno squalo 🦈": {"en": "A Shark 🦈", "es": "Un tiburón 🦈"},
    "Un micro-ragno macro-velenoso 🕷️": {"en": "A Micro-Spider, Mega-Venomous 🕷️", "es": "Una microaraña megavenenosa 🕷️"},
    "Uno scorpione velenoso 🦂": {"en": "A Venomous Scorpion 🦂", "es": "Un escorpión venenoso 🦂"},
    "Una zanzara gigante australiana 🦟": {"en": "A Giant Australian Mosquito 🦟", "es": "Un mosquito gigante australiano 🦟"},
    "Il covid 🦠": {"en": "Covid 🦠", "es": "El covid 🦠"},
    "Un silvantropo 🌳": {"en": "A Sylvanthrope 🌳", "es": "Un silvántropo 🌳"},
    "Un pino classico🌲": {"en": "A Classic Pine Tree 🌲", "es": "Un pino clásico 🌲"},
    "Un cespuglio rialzato 🌳": {"en": "A Raised Bush 🌳", "es": "Un arbusto elevado 🌳"},
    "Un  gamberetto 🦐": {"en": "A Shrimp 🦐", "es": "Un camarón 🦐"},
    "Una seppia 🦑": {"en": "A Cuttlefish 🦑", "es": "Una sepia 🦑"},
    "Un granchio da rave 🦀": {"en": "A Rave Crab 🦀", "es": "Un cangrejo de rave 🦀"},
    "Pizzicotta 🦞": {"en": "Pizzicotta 🦞", "es": "Pizzicotta 🦞"},
    "Il mostro dell'opera🎭": {"en": "The Monster of the Opera 🎭", "es": "El monstruo de la ópera 🎭"},
    "Il fantasma del teatro🎭": {"en": "The Theater Ghost 🎭", "es": "El fantasma del teatro 🎭"},
    "Un demonietto 👹": {"en": "A Little Demon 👹", "es": "Un diablillo 👹"},
    "Un bug di sistema 👾": {"en": "A System Bug 👾", "es": "Un error del sistema 👾"},
    "ClapTrap 🤖": {"en": "ClapTrap 🤖", "es": "ClapTrap 🤖"},
    "DeathTrap 🤖": {"en": "DeathTrap 🤖", "es": "DeathTrap 🤖"},
    "Un polipetto 🐙": {"en": "A Little Octopus 🐙", "es": "Un pulpito 🐙"},
    "Un craken di medie dimensioni 🐙": {"en": "A Medium-Sized Kraken 🐙", "es": "Un kraken mediano 🐙"},
})


def _wiki_data():
    import genera_wiki_v13 as wiki

    wiki.v3.v2.set_names = wiki.v3._valid_set_names
    return wiki.build_data()


def entity_rows(data):
    collections = {
        "set": data.get("sets", []),
        "ring": data.get("rings", []),
        "incantation": data.get("incantations", []),
        "item": data.get("items", []),
        "boss": data.get("bosses", []),
        "enemy": data.get("enemies", []),
        "location": data.get("locations", []),
        "room": data.get("dungeon", {}).get("rooms", []),
        "structure": data.get("assault", []),
        "approach": data.get("approaches", []),
        "nucleus": data.get("nuclei", []),
        "event": data.get("events", []),
        "modifier": data.get("modifiers", []),
        "scaglione": data.get("scaglioni", []),
        "achievement": data.get("achievements", []),
        "marine_boss": data.get("marine_bosses", []),
    }
    rows = []
    for kind, values in collections.items():
        for value in values:
            name = value.get("name") if isinstance(value, dict) else None
            if isinstance(name, str) and name.strip():
                rows.append((kind, name.strip()))

    # Termini dinamici mostrati dal bot ma non dotati di una pagina Wiki.
    # Gli ingredienti condividono il namespace degli oggetti perché finiscono
    # nello stesso zaino; gli altri mantengono un tipo distinto.
    import liste

    extra_collections = {
        "item": getattr(liste, "ingredienti", []),
        "pet": getattr(liste, "animaletti", []),
        "weather": getattr(liste, "Metei", []),
        "choice": getattr(liste, "scelte", []),
        "role": ["Nullatenente"],
    }
    for kind, values in extra_collections.items():
        for value in values:
            if isinstance(value, str) and value.strip():
                rows.append((kind, value.strip()))
    return rows


def slug(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii").lower()
    result = re.sub(r"[^a-z0-9]+", "-", ascii_value).strip("-")
    return result or "entity"


def load_existing():
    if not REGISTRY_PATH.exists():
        return {}
    with REGISTRY_PATH.open(encoding="utf-8") as stream:
        payload = json.load(stream)
    return payload.get("entities", {}) if isinstance(payload, dict) else {}


def allocate_id(namespace: str, name: str, used: dict[str, str]) -> str:
    base = f"{namespace}.{slug(name)}"
    if base not in used or used[base] == name:
        return base
    suffix = hashlib.sha256(name.encode("utf-8")).hexdigest()[:7]
    return f"{base}-{suffix}"


def build_records(rows, existing):
    existing_by_identity = {}
    for entity_id, record in existing.items():
        if not isinstance(record, dict):
            continue
        namespace = str(record.get("namespace") or entity_id.split(".", 1)[0])
        old_names = [record.get("legacy_name")]
        if isinstance(record.get("aliases"), list):
            old_names.extend(record["aliases"])
        for old_name in old_names:
            if isinstance(old_name, str) and old_name:
                existing_by_identity[(namespace, old_name)] = entity_id

    grouped = {}
    for kind, name in rows:
        namespace = NAMESPACE.get(kind, kind)
        grouped.setdefault((namespace, name), set()).add(kind)

    used = {entity_id: str(record.get("legacy_name") or "") for entity_id, record in existing.items() if isinstance(record, dict)}
    records = {}
    for (namespace, name), kinds in sorted(grouped.items(), key=lambda item: (item[0][0], item[0][1].casefold())):
        entity_id = existing_by_identity.get((namespace, name)) or allocate_id(namespace, name, used)
        used[entity_id] = name
        previous = existing.get(entity_id, {}) if isinstance(existing.get(entity_id), dict) else {}
        names = previous.get("names", {}) if isinstance(previous.get("names"), dict) else {}
        aliases = {
            str(value)
            for value in previous.get("aliases", [])
            if isinstance(value, str) and value and value != name
        }
        previous_name = previous.get("legacy_name")
        if isinstance(previous_name, str) and previous_name and previous_name != name:
            aliases.add(previous_name)
        records[entity_id] = {
            "namespace": namespace,
            "kind": sorted(kinds)[0],
            "kinds": sorted(kinds),
            "legacy_name": name,
            "aliases": sorted(aliases, key=str.casefold),
            "names": {
                "it": name,
                "en": str(names.get("en") or ""),
                "es": str(names.get("es") or ""),
            },
        }

    # Le entità rimosse restano risolvibili per poter leggere vecchi save.
    for entity_id, previous in existing.items():
        if entity_id in records or not isinstance(previous, dict):
            continue
        retained = dict(previous)
        retained["retired"] = True
        records[entity_id] = retained
    return records


def translate_records(records, it_en_model: Path | None, en_es_model: Path | None, force: bool):
    pending_names = []
    for record in records.values():
        if record.get("retired"):
            continue
        names = record["names"]
        source = names["it"]
        if force or not names.get("en") or not names.get("es"):
            pending_names.append(source)
    pending_names = sorted(set(pending_names), key=lambda value: (value.casefold(), value))
    if pending_names and (not it_en_model or not en_es_model):
        raise SystemExit("Servono --it-en-model e --en-es-model per le nuove entità")

    generated = {}
    if pending_names:
        protected = set(PROTECTED_WORDS) | {"NftChallengeBot", "Ermenegildo", "ElSalamino"}
        english = translate_many(pending_names, OfflineTranslator(it_en_model), protected)
        spanish = translate_many(english, OfflineTranslator(en_es_model), protected)
        for source, en, es in zip(pending_names, english, spanish):
            generated[source] = {
                "en": apply_glossary(en, "en") or source,
                "es": apply_glossary(es, "es") or source,
            }

    for record in records.values():
        source = record.get("legacy_name", "")
        names = record.setdefault("names", {"it": source})
        names["it"] = source
        if source in generated:
            names.update(generated[source])
        if source in NAME_OVERRIDES:
            names.update(NAME_OVERRIDES[source])
        for language in ("en", "es"):
            names[language] = str(names.get(language) or source)
    return len(pending_names)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--it-en-model", type=Path)
    parser.add_argument("--en-es-model", type=Path)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    rows = entity_rows(_wiki_data())
    records = build_records(rows, load_existing())
    translated = translate_records(records, args.it_en_model, args.en_es_model, args.force)
    payload = {
        "_meta": {
            "schema_version": 1,
            "fallback": "it",
            "languages": ["it", "en", "es"],
            "active_entities": sum(not value.get("retired", False) for value in records.values()),
        },
        "entities": dict(sorted(records.items())),
    }
    with REGISTRY_PATH.open("w", encoding="utf-8", newline="\n") as stream:
        json.dump(payload, stream, ensure_ascii=False, indent=2)
        stream.write("\n")
    print(f"Registro entità: {payload['_meta']['active_entities']} ID; {translated} nomi tradotti")


if __name__ == "__main__":
    main()
